// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: system/v1/system.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigInfo) Reset() {
	*x = ConfigInfo{}
	mi := &file_system_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigInfo) ProtoMessage() {}

func (x *ConfigInfo) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigInfo.ProtoReflect.Descriptor instead.
func (*ConfigInfo) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfigInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_system_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_system_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{2}
}

func (x *SetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetConfigRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SetConfigRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type ListConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsRequest) Reset() {
	*x = ListConfigsRequest{}
	mi := &file_system_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsRequest) ProtoMessage() {}

func (x *ListConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigsRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{3}
}

func (x *ListConfigsRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type ListConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ConfigInfo          `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsResponse) Reset() {
	*x = ListConfigsResponse{}
	mi := &file_system_v1_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsResponse) ProtoMessage() {}

func (x *ListConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigsResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{4}
}

func (x *ListConfigsResponse) GetConfigs() []*ConfigInfo {
	if x != nil {
		return x.Configs
	}
	return nil
}

type ProfitSharingRuleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Ratio         float64                `protobuf:"fixed64,5,opt,name=ratio,proto3" json:"ratio,omitempty"`
	FixedAmount   float64                `protobuf:"fixed64,6,opt,name=fixed_amount,json=fixedAmount,proto3" json:"fixed_amount,omitempty"`
	Unit          string                 `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	MinAmount     float64                `protobuf:"fixed64,8,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount     float64                `protobuf:"fixed64,9,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	Sort          int32                  `protobuf:"varint,10,opt,name=sort,proto3" json:"sort,omitempty"`
	Enabled       int32                  `protobuf:"varint,11,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Description   string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfitSharingRuleInfo) Reset() {
	*x = ProfitSharingRuleInfo{}
	mi := &file_system_v1_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfitSharingRuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfitSharingRuleInfo) ProtoMessage() {}

func (x *ProfitSharingRuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfitSharingRuleInfo.ProtoReflect.Descriptor instead.
func (*ProfitSharingRuleInfo) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{5}
}

func (x *ProfitSharingRuleInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProfitSharingRuleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfitSharingRuleInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProfitSharingRuleInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ProfitSharingRuleInfo) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *ProfitSharingRuleInfo) GetFixedAmount() float64 {
	if x != nil {
		return x.FixedAmount
	}
	return 0
}

func (x *ProfitSharingRuleInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ProfitSharingRuleInfo) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *ProfitSharingRuleInfo) GetMaxAmount() float64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *ProfitSharingRuleInfo) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProfitSharingRuleInfo) GetEnabled() int32 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

func (x *ProfitSharingRuleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetProfitSharingRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Enabled       int32                  `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfitSharingRulesRequest) Reset() {
	*x = GetProfitSharingRulesRequest{}
	mi := &file_system_v1_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfitSharingRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfitSharingRulesRequest) ProtoMessage() {}

func (x *GetProfitSharingRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfitSharingRulesRequest.ProtoReflect.Descriptor instead.
func (*GetProfitSharingRulesRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{6}
}

func (x *GetProfitSharingRulesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetProfitSharingRulesRequest) GetEnabled() int32 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

type GetProfitSharingRulesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Rules         []*ProfitSharingRuleInfo `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfitSharingRulesResponse) Reset() {
	*x = GetProfitSharingRulesResponse{}
	mi := &file_system_v1_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfitSharingRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfitSharingRulesResponse) ProtoMessage() {}

func (x *GetProfitSharingRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfitSharingRulesResponse.ProtoReflect.Descriptor instead.
func (*GetProfitSharingRulesResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfitSharingRulesResponse) GetRules() []*ProfitSharingRuleInfo {
	if x != nil {
		return x.Rules
	}
	return nil
}

type CreateProfitSharingRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Ratio         float64                `protobuf:"fixed64,4,opt,name=ratio,proto3" json:"ratio,omitempty"`
	FixedAmount   float64                `protobuf:"fixed64,5,opt,name=fixed_amount,json=fixedAmount,proto3" json:"fixed_amount,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	MinAmount     float64                `protobuf:"fixed64,7,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount     float64                `protobuf:"fixed64,8,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfitSharingRuleRequest) Reset() {
	*x = CreateProfitSharingRuleRequest{}
	mi := &file_system_v1_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfitSharingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfitSharingRuleRequest) ProtoMessage() {}

func (x *CreateProfitSharingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfitSharingRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateProfitSharingRuleRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{8}
}

func (x *CreateProfitSharingRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfitSharingRuleRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateProfitSharingRuleRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateProfitSharingRuleRequest) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *CreateProfitSharingRuleRequest) GetFixedAmount() float64 {
	if x != nil {
		return x.FixedAmount
	}
	return 0
}

func (x *CreateProfitSharingRuleRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *CreateProfitSharingRuleRequest) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *CreateProfitSharingRuleRequest) GetMaxAmount() float64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *CreateProfitSharingRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateProfitSharingRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ratio         float64                `protobuf:"fixed64,3,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Enabled       int32                  `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfitSharingRuleRequest) Reset() {
	*x = UpdateProfitSharingRuleRequest{}
	mi := &file_system_v1_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfitSharingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfitSharingRuleRequest) ProtoMessage() {}

func (x *UpdateProfitSharingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfitSharingRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfitSharingRuleRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProfitSharingRuleRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProfitSharingRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfitSharingRuleRequest) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *UpdateProfitSharingRuleRequest) GetEnabled() int32 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

type DeleteProfitSharingRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfitSharingRuleRequest) Reset() {
	*x = DeleteProfitSharingRuleRequest{}
	mi := &file_system_v1_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfitSharingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfitSharingRuleRequest) ProtoMessage() {}

func (x *DeleteProfitSharingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfitSharingRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfitSharingRuleRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProfitSharingRuleRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleResponse) Reset() {
	*x = DeleteRuleResponse{}
	mi := &file_system_v1_system_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleResponse) ProtoMessage() {}

func (x *DeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RiskControlInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	Action        string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	LimitValue    uint32                 `protobuf:"varint,7,opt,name=limit_value,json=limitValue,proto3" json:"limit_value,omitempty"`
	TimeWindow    uint32                 `protobuf:"varint,8,opt,name=time_window,json=timeWindow,proto3" json:"time_window,omitempty"`
	Enabled       int32                  `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskControlInfo) Reset() {
	*x = RiskControlInfo{}
	mi := &file_system_v1_system_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskControlInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskControlInfo) ProtoMessage() {}

func (x *RiskControlInfo) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskControlInfo.ProtoReflect.Descriptor instead.
func (*RiskControlInfo) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{12}
}

func (x *RiskControlInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RiskControlInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RiskControlInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RiskControlInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RiskControlInfo) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *RiskControlInfo) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RiskControlInfo) GetLimitValue() uint32 {
	if x != nil {
		return x.LimitValue
	}
	return 0
}

func (x *RiskControlInfo) GetTimeWindow() uint32 {
	if x != nil {
		return x.TimeWindow
	}
	return 0
}

func (x *RiskControlInfo) GetEnabled() int32 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

func (x *RiskControlInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetRiskControlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Enabled       int32                  `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiskControlsRequest) Reset() {
	*x = GetRiskControlsRequest{}
	mi := &file_system_v1_system_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiskControlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiskControlsRequest) ProtoMessage() {}

func (x *GetRiskControlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiskControlsRequest.ProtoReflect.Descriptor instead.
func (*GetRiskControlsRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{13}
}

func (x *GetRiskControlsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetRiskControlsRequest) GetEnabled() int32 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

type GetRiskControlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Controls      []*RiskControlInfo     `protobuf:"bytes,1,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiskControlsResponse) Reset() {
	*x = GetRiskControlsResponse{}
	mi := &file_system_v1_system_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiskControlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiskControlsResponse) ProtoMessage() {}

func (x *GetRiskControlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiskControlsResponse.ProtoReflect.Descriptor instead.
func (*GetRiskControlsResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{14}
}

func (x *GetRiskControlsResponse) GetControls() []*RiskControlInfo {
	if x != nil {
		return x.Controls
	}
	return nil
}

type CreateRiskControlRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code             string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Level            string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	TriggerCondition string                 `protobuf:"bytes,5,opt,name=trigger_condition,json=triggerCondition,proto3" json:"trigger_condition,omitempty"`
	Action           string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	LimitValue       uint32                 `protobuf:"varint,7,opt,name=limit_value,json=limitValue,proto3" json:"limit_value,omitempty"`
	TimeWindow       uint32                 `protobuf:"varint,8,opt,name=time_window,json=timeWindow,proto3" json:"time_window,omitempty"`
	Description      string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateRiskControlRequest) Reset() {
	*x = CreateRiskControlRequest{}
	mi := &file_system_v1_system_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRiskControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRiskControlRequest) ProtoMessage() {}

func (x *CreateRiskControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRiskControlRequest.ProtoReflect.Descriptor instead.
func (*CreateRiskControlRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{15}
}

func (x *CreateRiskControlRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRiskControlRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRiskControlRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateRiskControlRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CreateRiskControlRequest) GetTriggerCondition() string {
	if x != nil {
		return x.TriggerCondition
	}
	return ""
}

func (x *CreateRiskControlRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreateRiskControlRequest) GetLimitValue() uint32 {
	if x != nil {
		return x.LimitValue
	}
	return 0
}

func (x *CreateRiskControlRequest) GetTimeWindow() uint32 {
	if x != nil {
		return x.TimeWindow
	}
	return 0
}

func (x *CreateRiskControlRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateRiskControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       int32                  `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRiskControlRequest) Reset() {
	*x = UpdateRiskControlRequest{}
	mi := &file_system_v1_system_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRiskControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRiskControlRequest) ProtoMessage() {}

func (x *UpdateRiskControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRiskControlRequest.ProtoReflect.Descriptor instead.
func (*UpdateRiskControlRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateRiskControlRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRiskControlRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRiskControlRequest) GetEnabled() int32 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

type CheckRiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Device        string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRiskRequest) Reset() {
	*x = CheckRiskRequest{}
	mi := &file_system_v1_system_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRiskRequest) ProtoMessage() {}

func (x *CheckRiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRiskRequest.ProtoReflect.Descriptor instead.
func (*CheckRiskRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{17}
}

func (x *CheckRiskRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CheckRiskRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckRiskRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CheckRiskRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *CheckRiskRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CheckRiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pass          bool                   `protobuf:"varint,1,opt,name=pass,proto3" json:"pass,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRiskResponse) Reset() {
	*x = CheckRiskResponse{}
	mi := &file_system_v1_system_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRiskResponse) ProtoMessage() {}

func (x *CheckRiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRiskResponse.ProtoReflect.Descriptor instead.
func (*CheckRiskResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{18}
}

func (x *CheckRiskResponse) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

func (x *CheckRiskResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CheckRiskResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRiskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DomainInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Enabled       int32                  `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainInfo) Reset() {
	*x = DomainInfo{}
	mi := &file_system_v1_system_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainInfo) ProtoMessage() {}

func (x *DomainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainInfo.ProtoReflect.Descriptor instead.
func (*DomainInfo) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{19}
}

func (x *DomainInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DomainInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainInfo) GetEnabled() int32 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

type GetDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       int32                  `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainsRequest) Reset() {
	*x = GetDomainsRequest{}
	mi := &file_system_v1_system_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainsRequest) ProtoMessage() {}

func (x *GetDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainsRequest.ProtoReflect.Descriptor instead.
func (*GetDomainsRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{20}
}

func (x *GetDomainsRequest) GetEnabled() int32 {
	if x != nil {
		return x.Enabled
	}
	return 0
}

type GetDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []*DomainInfo          `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainsResponse) Reset() {
	*x = GetDomainsResponse{}
	mi := &file_system_v1_system_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainsResponse) ProtoMessage() {}

func (x *GetDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainsResponse.ProtoReflect.Descriptor instead.
func (*GetDomainsResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{21}
}

func (x *GetDomainsResponse) GetDomains() []*DomainInfo {
	if x != nil {
		return x.Domains
	}
	return nil
}

type AddDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDomainRequest) Reset() {
	*x = AddDomainRequest{}
	mi := &file_system_v1_system_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDomainRequest) ProtoMessage() {}

func (x *AddDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDomainRequest.ProtoReflect.Descriptor instead.
func (*AddDomainRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{22}
}

func (x *AddDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type CheckWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckWhitelistRequest) Reset() {
	*x = CheckWhitelistRequest{}
	mi := &file_system_v1_system_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWhitelistRequest) ProtoMessage() {}

func (x *CheckWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWhitelistRequest.ProtoReflect.Descriptor instead.
func (*CheckWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{23}
}

func (x *CheckWhitelistRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CheckWhitelistRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CheckWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Whitelisted   bool                   `protobuf:"varint,1,opt,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckWhitelistResponse) Reset() {
	*x = CheckWhitelistResponse{}
	mi := &file_system_v1_system_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWhitelistResponse) ProtoMessage() {}

func (x *CheckWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_system_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWhitelistResponse.ProtoReflect.Descriptor instead.
func (*CheckWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_system_proto_rawDescGZIP(), []int{24}
}

func (x *CheckWhitelistResponse) GetWhitelisted() bool {
	if x != nil {
		return x.Whitelisted
	}
	return false
}

var File_system_v1_system_proto protoreflect.FileDescriptor

const file_system_v1_system_proto_rawDesc = "" +
	"\n" +
	"\x16system/v1/system.proto\x12\tsystem.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xb7\x01\n" +
	"\n" +
	"ConfigInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"$\n" +
	"\x10GetConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"r\n" +
	"\x10SetConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\"*\n" +
	"\x12ListConfigsRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\"F\n" +
	"\x13ListConfigsResponse\x12/\n" +
	"\aconfigs\x18\x01 \x03(\v2\x15.system.v1.ConfigInfoR\aconfigs\"\xc0\x02\n" +
	"\x15ProfitSharingRuleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x14\n" +
	"\x05ratio\x18\x05 \x01(\x01R\x05ratio\x12!\n" +
	"\ffixed_amount\x18\x06 \x01(\x01R\vfixedAmount\x12\x12\n" +
	"\x04unit\x18\a \x01(\tR\x04unit\x12\x1d\n" +
	"\n" +
	"min_amount\x18\b \x01(\x01R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\t \x01(\x01R\tmaxAmount\x12\x12\n" +
	"\x04sort\x18\n" +
	" \x01(\x05R\x04sort\x12\x18\n" +
	"\aenabled\x18\v \x01(\x05R\aenabled\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\"L\n" +
	"\x1cGetProfitSharingRulesRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\x05R\aenabled\"W\n" +
	"\x1dGetProfitSharingRulesResponse\x126\n" +
	"\x05rules\x18\x01 \x03(\v2 .system.v1.ProfitSharingRuleInfoR\x05rules\"\x8b\x02\n" +
	"\x1eCreateProfitSharingRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x14\n" +
	"\x05ratio\x18\x04 \x01(\x01R\x05ratio\x12!\n" +
	"\ffixed_amount\x18\x05 \x01(\x01R\vfixedAmount\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12\x1d\n" +
	"\n" +
	"min_amount\x18\a \x01(\x01R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\b \x01(\x01R\tmaxAmount\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\"t\n" +
	"\x1eUpdateProfitSharingRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05ratio\x18\x03 \x01(\x01R\x05ratio\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\x05R\aenabled\"0\n" +
	"\x1eDeleteProfitSharingRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\".\n" +
	"\x12DeleteRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x89\x02\n" +
	"\x0fRiskControlInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1f\n" +
	"\vlimit_value\x18\a \x01(\rR\n" +
	"limitValue\x12\x1f\n" +
	"\vtime_window\x18\b \x01(\rR\n" +
	"timeWindow\x12\x18\n" +
	"\aenabled\x18\t \x01(\x05R\aenabled\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\"F\n" +
	"\x16GetRiskControlsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\x05R\aenabled\"Q\n" +
	"\x17GetRiskControlsResponse\x126\n" +
	"\bcontrols\x18\x01 \x03(\v2\x1a.system.v1.RiskControlInfoR\bcontrols\"\x95\x02\n" +
	"\x18CreateRiskControlRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12+\n" +
	"\x11trigger_condition\x18\x05 \x01(\tR\x10triggerCondition\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1f\n" +
	"\vlimit_value\x18\a \x01(\rR\n" +
	"limitValue\x12\x1f\n" +
	"\vtime_window\x18\b \x01(\rR\n" +
	"timeWindow\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\"X\n" +
	"\x18UpdateRiskControlRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\x05R\aenabled\"\x7f\n" +
	"\x10CheckRiskRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\"o\n" +
	"\x11CheckRiskResponse\x12\x12\n" +
	"\x04pass\x18\x01 \x01(\bR\x04pass\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"N\n" +
	"\n" +
	"DomainInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\x05R\aenabled\"-\n" +
	"\x11GetDomainsRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\x05R\aenabled\"E\n" +
	"\x12GetDomainsResponse\x12/\n" +
	"\adomains\x18\x01 \x03(\v2\x15.system.v1.DomainInfoR\adomains\"*\n" +
	"\x10AddDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\";\n" +
	"\x15CheckWhitelistRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\":\n" +
	"\x16CheckWhitelistResponse\x12 \n" +
	"\vwhitelisted\x18\x01 \x01(\bR\vwhitelisted2\xec\r\n" +
	"\x06System\x12d\n" +
	"\tGetConfig\x12\x1b.system.v1.GetConfigRequest\x1a\x15.system.v1.ConfigInfo\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/system/config/{key}\x12a\n" +
	"\tSetConfig\x12\x1b.system.v1.SetConfigRequest\x1a\x15.system.v1.ConfigInfo\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/system/config\x12l\n" +
	"\vListConfigs\x12\x1d.system.v1.ListConfigsRequest\x1a\x1e.system.v1.ListConfigsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/system/configs\x12\x97\x01\n" +
	"\x15GetProfitSharingRules\x12'.system.v1.GetProfitSharingRulesRequest\x1a(.system.v1.GetProfitSharingRulesResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/system/profit-sharing-rules\x12\x96\x01\n" +
	"\x17CreateProfitSharingRule\x12).system.v1.CreateProfitSharingRuleRequest\x1a .system.v1.ProfitSharingRuleInfo\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/system/profit-sharing-rules\x12\x9b\x01\n" +
	"\x17UpdateProfitSharingRule\x12).system.v1.UpdateProfitSharingRuleRequest\x1a .system.v1.ProfitSharingRuleInfo\"3\x82\xd3\xe4\x93\x02-:\x01*\x1a(/api/v1/system/profit-sharing-rules/{id}\x12\x95\x01\n" +
	"\x17DeleteProfitSharingRule\x12).system.v1.DeleteProfitSharingRuleRequest\x1a\x1d.system.v1.DeleteRuleResponse\"0\x82\xd3\xe4\x93\x02**(/api/v1/system/profit-sharing-rules/{id}\x12~\n" +
	"\x0fGetRiskControls\x12!.system.v1.GetRiskControlsRequest\x1a\".system.v1.GetRiskControlsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/system/risk-controls\x12}\n" +
	"\x11CreateRiskControl\x12#.system.v1.CreateRiskControlRequest\x1a\x1a.system.v1.RiskControlInfo\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/system/risk-controls\x12\x82\x01\n" +
	"\x11UpdateRiskControl\x12#.system.v1.UpdateRiskControlRequest\x1a\x1a.system.v1.RiskControlInfo\",\x82\xd3\xe4\x93\x02&:\x01*\x1a!/api/v1/system/risk-controls/{id}\x12l\n" +
	"\tCheckRisk\x12\x1b.system.v1.CheckRiskRequest\x1a\x1c.system.v1.CheckRiskResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/system/check-risk\x12i\n" +
	"\n" +
	"GetDomains\x12\x1c.system.v1.GetDomainsRequest\x1a\x1d.system.v1.GetDomainsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/system/domains\x12b\n" +
	"\tAddDomain\x12\x1b.system.v1.AddDomainRequest\x1a\x15.system.v1.DomainInfo\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/system/domains\x12\x80\x01\n" +
	"\x0eCheckWhitelist\x12 .system.v1.CheckWhitelistRequest\x1a!.system.v1.CheckWhitelistResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/system/check-whitelistB\x19Z\x17system/api/system/v1;v1b\x06proto3"

var (
	file_system_v1_system_proto_rawDescOnce sync.Once
	file_system_v1_system_proto_rawDescData []byte
)

func file_system_v1_system_proto_rawDescGZIP() []byte {
	file_system_v1_system_proto_rawDescOnce.Do(func() {
		file_system_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_v1_system_proto_rawDesc), len(file_system_v1_system_proto_rawDesc)))
	})
	return file_system_v1_system_proto_rawDescData
}

var file_system_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_system_v1_system_proto_goTypes = []any{
	(*ConfigInfo)(nil),                     // 0: system.v1.ConfigInfo
	(*GetConfigRequest)(nil),               // 1: system.v1.GetConfigRequest
	(*SetConfigRequest)(nil),               // 2: system.v1.SetConfigRequest
	(*ListConfigsRequest)(nil),             // 3: system.v1.ListConfigsRequest
	(*ListConfigsResponse)(nil),            // 4: system.v1.ListConfigsResponse
	(*ProfitSharingRuleInfo)(nil),          // 5: system.v1.ProfitSharingRuleInfo
	(*GetProfitSharingRulesRequest)(nil),   // 6: system.v1.GetProfitSharingRulesRequest
	(*GetProfitSharingRulesResponse)(nil),  // 7: system.v1.GetProfitSharingRulesResponse
	(*CreateProfitSharingRuleRequest)(nil), // 8: system.v1.CreateProfitSharingRuleRequest
	(*UpdateProfitSharingRuleRequest)(nil), // 9: system.v1.UpdateProfitSharingRuleRequest
	(*DeleteProfitSharingRuleRequest)(nil), // 10: system.v1.DeleteProfitSharingRuleRequest
	(*DeleteRuleResponse)(nil),             // 11: system.v1.DeleteRuleResponse
	(*RiskControlInfo)(nil),                // 12: system.v1.RiskControlInfo
	(*GetRiskControlsRequest)(nil),         // 13: system.v1.GetRiskControlsRequest
	(*GetRiskControlsResponse)(nil),        // 14: system.v1.GetRiskControlsResponse
	(*CreateRiskControlRequest)(nil),       // 15: system.v1.CreateRiskControlRequest
	(*UpdateRiskControlRequest)(nil),       // 16: system.v1.UpdateRiskControlRequest
	(*CheckRiskRequest)(nil),               // 17: system.v1.CheckRiskRequest
	(*CheckRiskResponse)(nil),              // 18: system.v1.CheckRiskResponse
	(*DomainInfo)(nil),                     // 19: system.v1.DomainInfo
	(*GetDomainsRequest)(nil),              // 20: system.v1.GetDomainsRequest
	(*GetDomainsResponse)(nil),             // 21: system.v1.GetDomainsResponse
	(*AddDomainRequest)(nil),               // 22: system.v1.AddDomainRequest
	(*CheckWhitelistRequest)(nil),          // 23: system.v1.CheckWhitelistRequest
	(*CheckWhitelistResponse)(nil),         // 24: system.v1.CheckWhitelistResponse
	(*timestamppb.Timestamp)(nil),          // 25: google.protobuf.Timestamp
}
var file_system_v1_system_proto_depIdxs = []int32{
	25, // 0: system.v1.ConfigInfo.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: system.v1.ListConfigsResponse.configs:type_name -> system.v1.ConfigInfo
	5,  // 2: system.v1.GetProfitSharingRulesResponse.rules:type_name -> system.v1.ProfitSharingRuleInfo
	12, // 3: system.v1.GetRiskControlsResponse.controls:type_name -> system.v1.RiskControlInfo
	19, // 4: system.v1.GetDomainsResponse.domains:type_name -> system.v1.DomainInfo
	1,  // 5: system.v1.System.GetConfig:input_type -> system.v1.GetConfigRequest
	2,  // 6: system.v1.System.SetConfig:input_type -> system.v1.SetConfigRequest
	3,  // 7: system.v1.System.ListConfigs:input_type -> system.v1.ListConfigsRequest
	6,  // 8: system.v1.System.GetProfitSharingRules:input_type -> system.v1.GetProfitSharingRulesRequest
	8,  // 9: system.v1.System.CreateProfitSharingRule:input_type -> system.v1.CreateProfitSharingRuleRequest
	9,  // 10: system.v1.System.UpdateProfitSharingRule:input_type -> system.v1.UpdateProfitSharingRuleRequest
	10, // 11: system.v1.System.DeleteProfitSharingRule:input_type -> system.v1.DeleteProfitSharingRuleRequest
	13, // 12: system.v1.System.GetRiskControls:input_type -> system.v1.GetRiskControlsRequest
	15, // 13: system.v1.System.CreateRiskControl:input_type -> system.v1.CreateRiskControlRequest
	16, // 14: system.v1.System.UpdateRiskControl:input_type -> system.v1.UpdateRiskControlRequest
	17, // 15: system.v1.System.CheckRisk:input_type -> system.v1.CheckRiskRequest
	20, // 16: system.v1.System.GetDomains:input_type -> system.v1.GetDomainsRequest
	22, // 17: system.v1.System.AddDomain:input_type -> system.v1.AddDomainRequest
	23, // 18: system.v1.System.CheckWhitelist:input_type -> system.v1.CheckWhitelistRequest
	0,  // 19: system.v1.System.GetConfig:output_type -> system.v1.ConfigInfo
	0,  // 20: system.v1.System.SetConfig:output_type -> system.v1.ConfigInfo
	4,  // 21: system.v1.System.ListConfigs:output_type -> system.v1.ListConfigsResponse
	7,  // 22: system.v1.System.GetProfitSharingRules:output_type -> system.v1.GetProfitSharingRulesResponse
	5,  // 23: system.v1.System.CreateProfitSharingRule:output_type -> system.v1.ProfitSharingRuleInfo
	5,  // 24: system.v1.System.UpdateProfitSharingRule:output_type -> system.v1.ProfitSharingRuleInfo
	11, // 25: system.v1.System.DeleteProfitSharingRule:output_type -> system.v1.DeleteRuleResponse
	14, // 26: system.v1.System.GetRiskControls:output_type -> system.v1.GetRiskControlsResponse
	12, // 27: system.v1.System.CreateRiskControl:output_type -> system.v1.RiskControlInfo
	12, // 28: system.v1.System.UpdateRiskControl:output_type -> system.v1.RiskControlInfo
	18, // 29: system.v1.System.CheckRisk:output_type -> system.v1.CheckRiskResponse
	21, // 30: system.v1.System.GetDomains:output_type -> system.v1.GetDomainsResponse
	19, // 31: system.v1.System.AddDomain:output_type -> system.v1.DomainInfo
	24, // 32: system.v1.System.CheckWhitelist:output_type -> system.v1.CheckWhitelistResponse
	19, // [19:33] is the sub-list for method output_type
	5,  // [5:19] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_system_v1_system_proto_init() }
func file_system_v1_system_proto_init() {
	if File_system_v1_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_v1_system_proto_rawDesc), len(file_system_v1_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_v1_system_proto_goTypes,
		DependencyIndexes: file_system_v1_system_proto_depIdxs,
		MessageInfos:      file_system_v1_system_proto_msgTypes,
	}.Build()
	File_system_v1_system_proto = out.File
	file_system_v1_system_proto_goTypes = nil
	file_system_v1_system_proto_depIdxs = nil
}
