// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"system/internal/biz"
	"system/internal/conf"
	"system/internal/data"
	"system/internal/server"
	"system/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	configRepo := data.NewConfigRepo(dataData, logger)
	profitSharingRepo := data.NewProfitSharingRepo(dataData, logger)
	riskControlRepo := data.NewRiskControlRepo(dataData, logger)
	domainRepo := data.NewDomainRepo(dataData, logger)
	whitelistRepo := data.NewWhitelistRepo(dataData, logger)
	systemUsecase := biz.NewSystemUsecase(configRepo, profitSharingRepo, riskControlRepo, domainRepo, whitelistRepo, logger)
	systemService := service.NewSystemService(systemUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, systemService, logger)
	httpServer := server.NewHTTPServer(confServer, systemService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
