// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: sms/v1/sms.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmsService_SendSms_FullMethodName        = "/api.sms.v1.SmsService/SendSms"
	SmsService_BatchSendSms_FullMethodName   = "/api.sms.v1.SmsService/BatchSendSms"
	SmsService_GetSmsLog_FullMethodName      = "/api.sms.v1.SmsService/GetSmsLog"
	SmsService_ListSmsLogs_FullMethodName    = "/api.sms.v1.SmsService/ListSmsLogs"
	SmsService_GetProviders_FullMethodName   = "/api.sms.v1.SmsService/GetProviders"
	SmsService_SwitchProvider_FullMethodName = "/api.sms.v1.SmsService/SwitchProvider"
)

// SmsServiceClient is the client API for SmsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SMS 短信服务
type SmsServiceClient interface {
	// 发送短信
	SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsReply, error)
	// 批量发送短信
	BatchSendSms(ctx context.Context, in *BatchSendSmsRequest, opts ...grpc.CallOption) (*BatchSendSmsReply, error)
	// 获取短信发送记录
	GetSmsLog(ctx context.Context, in *GetSmsLogRequest, opts ...grpc.CallOption) (*SmsLog, error)
	// 查询短信发送记录列表
	ListSmsLogs(ctx context.Context, in *ListSmsLogsRequest, opts ...grpc.CallOption) (*ListSmsLogsReply, error)
	// 获取所有短信服务商
	GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*GetProvidersReply, error)
	// 切换默认短信服务商
	SwitchProvider(ctx context.Context, in *SwitchProviderRequest, opts ...grpc.CallOption) (*SwitchProviderReply, error)
}

type smsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmsServiceClient(cc grpc.ClientConnInterface) SmsServiceClient {
	return &smsServiceClient{cc}
}

func (c *smsServiceClient) SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSmsReply)
	err := c.cc.Invoke(ctx, SmsService_SendSms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsServiceClient) BatchSendSms(ctx context.Context, in *BatchSendSmsRequest, opts ...grpc.CallOption) (*BatchSendSmsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSendSmsReply)
	err := c.cc.Invoke(ctx, SmsService_BatchSendSms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsServiceClient) GetSmsLog(ctx context.Context, in *GetSmsLogRequest, opts ...grpc.CallOption) (*SmsLog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmsLog)
	err := c.cc.Invoke(ctx, SmsService_GetSmsLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsServiceClient) ListSmsLogs(ctx context.Context, in *ListSmsLogsRequest, opts ...grpc.CallOption) (*ListSmsLogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSmsLogsReply)
	err := c.cc.Invoke(ctx, SmsService_ListSmsLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsServiceClient) GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*GetProvidersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProvidersReply)
	err := c.cc.Invoke(ctx, SmsService_GetProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsServiceClient) SwitchProvider(ctx context.Context, in *SwitchProviderRequest, opts ...grpc.CallOption) (*SwitchProviderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchProviderReply)
	err := c.cc.Invoke(ctx, SmsService_SwitchProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsServiceServer is the server API for SmsService service.
// All implementations must embed UnimplementedSmsServiceServer
// for forward compatibility.
//
// SMS 短信服务
type SmsServiceServer interface {
	// 发送短信
	SendSms(context.Context, *SendSmsRequest) (*SendSmsReply, error)
	// 批量发送短信
	BatchSendSms(context.Context, *BatchSendSmsRequest) (*BatchSendSmsReply, error)
	// 获取短信发送记录
	GetSmsLog(context.Context, *GetSmsLogRequest) (*SmsLog, error)
	// 查询短信发送记录列表
	ListSmsLogs(context.Context, *ListSmsLogsRequest) (*ListSmsLogsReply, error)
	// 获取所有短信服务商
	GetProviders(context.Context, *GetProvidersRequest) (*GetProvidersReply, error)
	// 切换默认短信服务商
	SwitchProvider(context.Context, *SwitchProviderRequest) (*SwitchProviderReply, error)
	mustEmbedUnimplementedSmsServiceServer()
}

// UnimplementedSmsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmsServiceServer struct{}

func (UnimplementedSmsServiceServer) SendSms(context.Context, *SendSmsRequest) (*SendSmsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSms not implemented")
}
func (UnimplementedSmsServiceServer) BatchSendSms(context.Context, *BatchSendSmsRequest) (*BatchSendSmsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchSendSms not implemented")
}
func (UnimplementedSmsServiceServer) GetSmsLog(context.Context, *GetSmsLogRequest) (*SmsLog, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSmsLog not implemented")
}
func (UnimplementedSmsServiceServer) ListSmsLogs(context.Context, *ListSmsLogsRequest) (*ListSmsLogsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSmsLogs not implemented")
}
func (UnimplementedSmsServiceServer) GetProviders(context.Context, *GetProvidersRequest) (*GetProvidersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviders not implemented")
}
func (UnimplementedSmsServiceServer) SwitchProvider(context.Context, *SwitchProviderRequest) (*SwitchProviderReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SwitchProvider not implemented")
}
func (UnimplementedSmsServiceServer) mustEmbedUnimplementedSmsServiceServer() {}
func (UnimplementedSmsServiceServer) testEmbeddedByValue()                    {}

// UnsafeSmsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmsServiceServer will
// result in compilation errors.
type UnsafeSmsServiceServer interface {
	mustEmbedUnimplementedSmsServiceServer()
}

func RegisterSmsServiceServer(s grpc.ServiceRegistrar, srv SmsServiceServer) {
	// If the following call panics, it indicates UnimplementedSmsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmsService_ServiceDesc, srv)
}

func _SmsService_SendSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServiceServer).SendSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmsService_SendSms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServiceServer).SendSms(ctx, req.(*SendSmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsService_BatchSendSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSendSmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServiceServer).BatchSendSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmsService_BatchSendSms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServiceServer).BatchSendSms(ctx, req.(*BatchSendSmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsService_GetSmsLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSmsLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServiceServer).GetSmsLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmsService_GetSmsLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServiceServer).GetSmsLog(ctx, req.(*GetSmsLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsService_ListSmsLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSmsLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServiceServer).ListSmsLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmsService_ListSmsLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServiceServer).ListSmsLogs(ctx, req.(*ListSmsLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsService_GetProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServiceServer).GetProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmsService_GetProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServiceServer).GetProviders(ctx, req.(*GetProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsService_SwitchProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServiceServer).SwitchProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmsService_SwitchProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServiceServer).SwitchProvider(ctx, req.(*SwitchProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmsService_ServiceDesc is the grpc.ServiceDesc for SmsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.sms.v1.SmsService",
	HandlerType: (*SmsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSms",
			Handler:    _SmsService_SendSms_Handler,
		},
		{
			MethodName: "BatchSendSms",
			Handler:    _SmsService_BatchSendSms_Handler,
		},
		{
			MethodName: "GetSmsLog",
			Handler:    _SmsService_GetSmsLog_Handler,
		},
		{
			MethodName: "ListSmsLogs",
			Handler:    _SmsService_ListSmsLogs_Handler,
		},
		{
			MethodName: "GetProviders",
			Handler:    _SmsService_GetProviders_Handler,
		},
		{
			MethodName: "SwitchProvider",
			Handler:    _SmsService_SwitchProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sms/v1/sms.proto",
}
