// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: finance/v1/finance.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RechargeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InviteCode    string                 `protobuf:"bytes,3,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	OrderNo       string                 `protobuf:"bytes,6,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeInfo) Reset() {
	*x = RechargeInfo{}
	mi := &file_finance_v1_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeInfo) ProtoMessage() {}

func (x *RechargeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeInfo.ProtoReflect.Descriptor instead.
func (*RechargeInfo) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{0}
}

func (x *RechargeInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RechargeInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RechargeInfo) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *RechargeInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RechargeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RechargeInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *RechargeInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RechargeInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RechargeInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RechargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ChannelCode   string                 `protobuf:"bytes,3,opt,name=channel_code,json=channelCode,proto3" json:"channel_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeRequest) Reset() {
	*x = RechargeRequest{}
	mi := &file_finance_v1_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeRequest) ProtoMessage() {}

func (x *RechargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeRequest.ProtoReflect.Descriptor instead.
func (*RechargeRequest) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{1}
}

func (x *RechargeRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RechargeRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RechargeRequest) GetChannelCode() string {
	if x != nil {
		return x.ChannelCode
	}
	return ""
}

type GetRechargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRechargeRequest) Reset() {
	*x = GetRechargeRequest{}
	mi := &file_finance_v1_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRechargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRechargeRequest) ProtoMessage() {}

func (x *GetRechargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRechargeRequest.ProtoReflect.Descriptor instead.
func (*GetRechargeRequest) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{2}
}

func (x *GetRechargeRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type ListRechargesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRechargesRequest) Reset() {
	*x = ListRechargesRequest{}
	mi := &file_finance_v1_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRechargesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRechargesRequest) ProtoMessage() {}

func (x *ListRechargesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRechargesRequest.ProtoReflect.Descriptor instead.
func (*ListRechargesRequest) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{3}
}

func (x *ListRechargesRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListRechargesRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListRechargesRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRechargesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRechargesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recharges     []*RechargeInfo        `protobuf:"bytes,1,rep,name=recharges,proto3" json:"recharges,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRechargesResponse) Reset() {
	*x = ListRechargesResponse{}
	mi := &file_finance_v1_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRechargesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRechargesResponse) ProtoMessage() {}

func (x *ListRechargesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRechargesResponse.ProtoReflect.Descriptor instead.
func (*ListRechargesResponse) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{4}
}

func (x *ListRechargesResponse) GetRecharges() []*RechargeInfo {
	if x != nil {
		return x.Recharges
	}
	return nil
}

func (x *ListRechargesResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WithdrawalInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	BankCard      string                 `protobuf:"bytes,5,opt,name=bank_card,json=bankCard,proto3" json:"bank_card,omitempty"`
	BankName      string                 `protobuf:"bytes,6,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawalInfo) Reset() {
	*x = WithdrawalInfo{}
	mi := &file_finance_v1_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawalInfo) ProtoMessage() {}

func (x *WithdrawalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawalInfo.ProtoReflect.Descriptor instead.
func (*WithdrawalInfo) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{5}
}

func (x *WithdrawalInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WithdrawalInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WithdrawalInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *WithdrawalInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WithdrawalInfo) GetBankCard() string {
	if x != nil {
		return x.BankCard
	}
	return ""
}

func (x *WithdrawalInfo) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *WithdrawalInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawalInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WithdrawalInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *WithdrawalInfo) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *WithdrawalInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type WithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	BankCard      string                 `protobuf:"bytes,3,opt,name=bank_card,json=bankCard,proto3" json:"bank_card,omitempty"`
	BankName      string                 `protobuf:"bytes,4,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	mi := &file_finance_v1_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{6}
}

func (x *WithdrawRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WithdrawRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawRequest) GetBankCard() string {
	if x != nil {
		return x.BankCard
	}
	return ""
}

func (x *WithdrawRequest) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

type GetWithdrawalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawalRequest) Reset() {
	*x = GetWithdrawalRequest{}
	mi := &file_finance_v1_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawalRequest) ProtoMessage() {}

func (x *GetWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*GetWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{7}
}

func (x *GetWithdrawalRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListWithdrawalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWithdrawalsRequest) Reset() {
	*x = ListWithdrawalsRequest{}
	mi := &file_finance_v1_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWithdrawalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWithdrawalsRequest) ProtoMessage() {}

func (x *ListWithdrawalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWithdrawalsRequest.ProtoReflect.Descriptor instead.
func (*ListWithdrawalsRequest) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{8}
}

func (x *ListWithdrawalsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListWithdrawalsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListWithdrawalsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWithdrawalsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListWithdrawalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Withdrawals   []*WithdrawalInfo      `protobuf:"bytes,1,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWithdrawalsResponse) Reset() {
	*x = ListWithdrawalsResponse{}
	mi := &file_finance_v1_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWithdrawalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWithdrawalsResponse) ProtoMessage() {}

func (x *ListWithdrawalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWithdrawalsResponse.ProtoReflect.Descriptor instead.
func (*ListWithdrawalsResponse) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{9}
}

func (x *ListWithdrawalsResponse) GetWithdrawals() []*WithdrawalInfo {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

func (x *ListWithdrawalsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type IncomeLogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	SourceType    int32                  `protobuf:"varint,6,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	RelatedId     uint32                 `protobuf:"varint,8,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomeLogInfo) Reset() {
	*x = IncomeLogInfo{}
	mi := &file_finance_v1_finance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomeLogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomeLogInfo) ProtoMessage() {}

func (x *IncomeLogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomeLogInfo.ProtoReflect.Descriptor instead.
func (*IncomeLogInfo) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{10}
}

func (x *IncomeLogInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IncomeLogInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IncomeLogInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *IncomeLogInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IncomeLogInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IncomeLogInfo) GetSourceType() int32 {
	if x != nil {
		return x.SourceType
	}
	return 0
}

func (x *IncomeLogInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *IncomeLogInfo) GetRelatedId() uint32 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *IncomeLogInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListIncomeLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SourceType    int32                  `protobuf:"varint,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncomeLogsRequest) Reset() {
	*x = ListIncomeLogsRequest{}
	mi := &file_finance_v1_finance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncomeLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncomeLogsRequest) ProtoMessage() {}

func (x *ListIncomeLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncomeLogsRequest.ProtoReflect.Descriptor instead.
func (*ListIncomeLogsRequest) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{11}
}

func (x *ListIncomeLogsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListIncomeLogsRequest) GetSourceType() int32 {
	if x != nil {
		return x.SourceType
	}
	return 0
}

func (x *ListIncomeLogsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListIncomeLogsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListIncomeLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncomeLogs    []*IncomeLogInfo       `protobuf:"bytes,1,rep,name=income_logs,json=incomeLogs,proto3" json:"income_logs,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncomeLogsResponse) Reset() {
	*x = ListIncomeLogsResponse{}
	mi := &file_finance_v1_finance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncomeLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncomeLogsResponse) ProtoMessage() {}

func (x *ListIncomeLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncomeLogsResponse.ProtoReflect.Descriptor instead.
func (*ListIncomeLogsResponse) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{12}
}

func (x *ListIncomeLogsResponse) GetIncomeLogs() []*IncomeLogInfo {
	if x != nil {
		return x.IncomeLogs
	}
	return nil
}

func (x *ListIncomeLogsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BalanceLogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	BeforeBalance float64                `protobuf:"fixed64,5,opt,name=before_balance,json=beforeBalance,proto3" json:"before_balance,omitempty"`
	AfterBalance  float64                `protobuf:"fixed64,6,opt,name=after_balance,json=afterBalance,proto3" json:"after_balance,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	RelatedId     uint32                 `protobuf:"varint,8,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceLogInfo) Reset() {
	*x = BalanceLogInfo{}
	mi := &file_finance_v1_finance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceLogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceLogInfo) ProtoMessage() {}

func (x *BalanceLogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceLogInfo.ProtoReflect.Descriptor instead.
func (*BalanceLogInfo) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{13}
}

func (x *BalanceLogInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BalanceLogInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BalanceLogInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BalanceLogInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BalanceLogInfo) GetBeforeBalance() float64 {
	if x != nil {
		return x.BeforeBalance
	}
	return 0
}

func (x *BalanceLogInfo) GetAfterBalance() float64 {
	if x != nil {
		return x.AfterBalance
	}
	return 0
}

func (x *BalanceLogInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BalanceLogInfo) GetRelatedId() uint32 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *BalanceLogInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListBalanceLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBalanceLogsRequest) Reset() {
	*x = ListBalanceLogsRequest{}
	mi := &file_finance_v1_finance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBalanceLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBalanceLogsRequest) ProtoMessage() {}

func (x *ListBalanceLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBalanceLogsRequest.ProtoReflect.Descriptor instead.
func (*ListBalanceLogsRequest) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{14}
}

func (x *ListBalanceLogsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListBalanceLogsRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ListBalanceLogsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBalanceLogsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBalanceLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BalanceLogs   []*BalanceLogInfo      `protobuf:"bytes,1,rep,name=balance_logs,json=balanceLogs,proto3" json:"balance_logs,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBalanceLogsResponse) Reset() {
	*x = ListBalanceLogsResponse{}
	mi := &file_finance_v1_finance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBalanceLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBalanceLogsResponse) ProtoMessage() {}

func (x *ListBalanceLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBalanceLogsResponse.ProtoReflect.Descriptor instead.
func (*ListBalanceLogsResponse) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{15}
}

func (x *ListBalanceLogsResponse) GetBalanceLogs() []*BalanceLogInfo {
	if x != nil {
		return x.BalanceLogs
	}
	return nil
}

func (x *ListBalanceLogsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_finance_v1_finance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{16}
}

func (x *CheckInRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckInResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ConsecutiveDays uint32                 `protobuf:"varint,2,opt,name=consecutive_days,json=consecutiveDays,proto3" json:"consecutive_days,omitempty"`
	RewardPoints    float64                `protobuf:"fixed64,3,opt,name=reward_points,json=rewardPoints,proto3" json:"reward_points,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	mi := &file_finance_v1_finance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{17}
}

func (x *CheckInResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckInResponse) GetConsecutiveDays() uint32 {
	if x != nil {
		return x.ConsecutiveDays
	}
	return 0
}

func (x *CheckInResponse) GetRewardPoints() float64 {
	if x != nil {
		return x.RewardPoints
	}
	return 0
}

type UserBalanceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	WorkPoints    float64                `protobuf:"fixed64,3,opt,name=work_points,json=workPoints,proto3" json:"work_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBalanceInfo) Reset() {
	*x = UserBalanceInfo{}
	mi := &file_finance_v1_finance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBalanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalanceInfo) ProtoMessage() {}

func (x *UserBalanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalanceInfo.ProtoReflect.Descriptor instead.
func (*UserBalanceInfo) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{18}
}

func (x *UserBalanceInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserBalanceInfo) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UserBalanceInfo) GetWorkPoints() float64 {
	if x != nil {
		return x.WorkPoints
	}
	return 0
}

type GetUserBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceRequest) Reset() {
	*x = GetUserBalanceRequest{}
	mi := &file_finance_v1_finance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceRequest) ProtoMessage() {}

func (x *GetUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_v1_finance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_finance_v1_finance_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserBalanceRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_finance_v1_finance_proto protoreflect.FileDescriptor

const file_finance_v1_finance_proto_rawDesc = "" +
	"\n" +
	"\x18finance/v1/finance.proto\x12\n" +
	"finance.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x88\x02\n" +
	"\fRechargeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1f\n" +
	"\vinvite_code\x18\x03 \x01(\tR\n" +
	"inviteCode\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x19\n" +
	"\border_no\x18\x06 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"e\n" +
	"\x0fRechargeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12!\n" +
	"\fchannel_code\x18\x03 \x01(\tR\vchannelCode\"/\n" +
	"\x12GetRechargeRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"x\n" +
	"\x14ListRechargesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"e\n" +
	"\x15ListRechargesResponse\x126\n" +
	"\trecharges\x18\x01 \x03(\v2\x18.finance.v1.RechargeInfoR\trecharges\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"\xdf\x02\n" +
	"\x0eWithdrawalInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1b\n" +
	"\tbank_card\x18\x05 \x01(\tR\bbankCard\x12\x1b\n" +
	"\tbank_name\x18\x06 \x01(\tR\bbankName\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12=\n" +
	"\fprocessed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"|\n" +
	"\x0fWithdrawRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1b\n" +
	"\tbank_card\x18\x03 \x01(\tR\bbankCard\x12\x1b\n" +
	"\tbank_name\x18\x04 \x01(\tR\bbankName\"&\n" +
	"\x14GetWithdrawalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"z\n" +
	"\x16ListWithdrawalsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"m\n" +
	"\x17ListWithdrawalsResponse\x12<\n" +
	"\vwithdrawals\x18\x01 \x03(\v2\x1a.finance.v1.WithdrawalInfoR\vwithdrawals\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"\x8d\x02\n" +
	"\rIncomeLogInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1f\n" +
	"\vsource_type\x18\x06 \x01(\x05R\n" +
	"sourceType\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"related_id\x18\b \x01(\rR\trelatedId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x82\x01\n" +
	"\x15ListIncomeLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\x05R\n" +
	"sourceType\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"j\n" +
	"\x16ListIncomeLogsResponse\x12:\n" +
	"\vincome_logs\x18\x01 \x03(\v2\x19.finance.v1.IncomeLogInfoR\n" +
	"incomeLogs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"\xa3\x02\n" +
	"\x0eBalanceLogInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12%\n" +
	"\x0ebefore_balance\x18\x05 \x01(\x01R\rbeforeBalance\x12#\n" +
	"\rafter_balance\x18\x06 \x01(\x01R\fafterBalance\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"related_id\x18\b \x01(\rR\trelatedId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"v\n" +
	"\x16ListBalanceLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"n\n" +
	"\x17ListBalanceLogsResponse\x12=\n" +
	"\fbalance_logs\x18\x01 \x03(\v2\x1a.finance.v1.BalanceLogInfoR\vbalanceLogs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\")\n" +
	"\x0eCheckInRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"{\n" +
	"\x0fCheckInResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10consecutive_days\x18\x02 \x01(\rR\x0fconsecutiveDays\x12#\n" +
	"\rreward_points\x18\x03 \x01(\x01R\frewardPoints\"e\n" +
	"\x0fUserBalanceInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x1f\n" +
	"\vwork_points\x18\x03 \x01(\x01R\n" +
	"workPoints\"0\n" +
	"\x15GetUserBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId2\xa9\t\n" +
	"\aFinance\x12f\n" +
	"\bRecharge\x12\x1b.finance.v1.RechargeRequest\x1a\x18.finance.v1.RechargeInfo\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/finance/recharge\x12t\n" +
	"\vGetRecharge\x12\x1e.finance.v1.GetRechargeRequest\x1a\x18.finance.v1.RechargeInfo\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/finance/recharge/{order_no}\x12w\n" +
	"\rListRecharges\x12 .finance.v1.ListRechargesRequest\x1a!.finance.v1.ListRechargesResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/finance/recharges\x12h\n" +
	"\bWithdraw\x12\x1b.finance.v1.WithdrawRequest\x1a\x1a.finance.v1.WithdrawalInfo\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/finance/withdraw\x12v\n" +
	"\rGetWithdrawal\x12 .finance.v1.GetWithdrawalRequest\x1a\x1a.finance.v1.WithdrawalInfo\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/finance/withdrawal/{id}\x12\x7f\n" +
	"\x0fListWithdrawals\x12\".finance.v1.ListWithdrawalsRequest\x1a#.finance.v1.ListWithdrawalsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/finance/withdrawals\x12|\n" +
	"\x0eListIncomeLogs\x12!.finance.v1.ListIncomeLogsRequest\x1a\".finance.v1.ListIncomeLogsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/finance/income-logs\x12\x80\x01\n" +
	"\x0fListBalanceLogs\x12\".finance.v1.ListBalanceLogsRequest\x1a#.finance.v1.ListBalanceLogsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/finance/balance-logs\x12f\n" +
	"\aCheckIn\x12\x1a.finance.v1.CheckInRequest\x1a\x1b.finance.v1.CheckInResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/finance/checkin\x12{\n" +
	"\x0eGetUserBalance\x12!.finance.v1.GetUserBalanceRequest\x1a\x1b.finance.v1.UserBalanceInfo\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/finance/balance/{user_id}B\x1bZ\x19finance/api/finance/v1;v1b\x06proto3"

var (
	file_finance_v1_finance_proto_rawDescOnce sync.Once
	file_finance_v1_finance_proto_rawDescData []byte
)

func file_finance_v1_finance_proto_rawDescGZIP() []byte {
	file_finance_v1_finance_proto_rawDescOnce.Do(func() {
		file_finance_v1_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finance_v1_finance_proto_rawDesc), len(file_finance_v1_finance_proto_rawDesc)))
	})
	return file_finance_v1_finance_proto_rawDescData
}

var file_finance_v1_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_finance_v1_finance_proto_goTypes = []any{
	(*RechargeInfo)(nil),            // 0: finance.v1.RechargeInfo
	(*RechargeRequest)(nil),         // 1: finance.v1.RechargeRequest
	(*GetRechargeRequest)(nil),      // 2: finance.v1.GetRechargeRequest
	(*ListRechargesRequest)(nil),    // 3: finance.v1.ListRechargesRequest
	(*ListRechargesResponse)(nil),   // 4: finance.v1.ListRechargesResponse
	(*WithdrawalInfo)(nil),          // 5: finance.v1.WithdrawalInfo
	(*WithdrawRequest)(nil),         // 6: finance.v1.WithdrawRequest
	(*GetWithdrawalRequest)(nil),    // 7: finance.v1.GetWithdrawalRequest
	(*ListWithdrawalsRequest)(nil),  // 8: finance.v1.ListWithdrawalsRequest
	(*ListWithdrawalsResponse)(nil), // 9: finance.v1.ListWithdrawalsResponse
	(*IncomeLogInfo)(nil),           // 10: finance.v1.IncomeLogInfo
	(*ListIncomeLogsRequest)(nil),   // 11: finance.v1.ListIncomeLogsRequest
	(*ListIncomeLogsResponse)(nil),  // 12: finance.v1.ListIncomeLogsResponse
	(*BalanceLogInfo)(nil),          // 13: finance.v1.BalanceLogInfo
	(*ListBalanceLogsRequest)(nil),  // 14: finance.v1.ListBalanceLogsRequest
	(*ListBalanceLogsResponse)(nil), // 15: finance.v1.ListBalanceLogsResponse
	(*CheckInRequest)(nil),          // 16: finance.v1.CheckInRequest
	(*CheckInResponse)(nil),         // 17: finance.v1.CheckInResponse
	(*UserBalanceInfo)(nil),         // 18: finance.v1.UserBalanceInfo
	(*GetUserBalanceRequest)(nil),   // 19: finance.v1.GetUserBalanceRequest
	(*timestamppb.Timestamp)(nil),   // 20: google.protobuf.Timestamp
}
var file_finance_v1_finance_proto_depIdxs = []int32{
	20, // 0: finance.v1.RechargeInfo.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: finance.v1.ListRechargesResponse.recharges:type_name -> finance.v1.RechargeInfo
	20, // 2: finance.v1.WithdrawalInfo.processed_at:type_name -> google.protobuf.Timestamp
	20, // 3: finance.v1.WithdrawalInfo.created_at:type_name -> google.protobuf.Timestamp
	5,  // 4: finance.v1.ListWithdrawalsResponse.withdrawals:type_name -> finance.v1.WithdrawalInfo
	20, // 5: finance.v1.IncomeLogInfo.created_at:type_name -> google.protobuf.Timestamp
	10, // 6: finance.v1.ListIncomeLogsResponse.income_logs:type_name -> finance.v1.IncomeLogInfo
	20, // 7: finance.v1.BalanceLogInfo.created_at:type_name -> google.protobuf.Timestamp
	13, // 8: finance.v1.ListBalanceLogsResponse.balance_logs:type_name -> finance.v1.BalanceLogInfo
	1,  // 9: finance.v1.Finance.Recharge:input_type -> finance.v1.RechargeRequest
	2,  // 10: finance.v1.Finance.GetRecharge:input_type -> finance.v1.GetRechargeRequest
	3,  // 11: finance.v1.Finance.ListRecharges:input_type -> finance.v1.ListRechargesRequest
	6,  // 12: finance.v1.Finance.Withdraw:input_type -> finance.v1.WithdrawRequest
	7,  // 13: finance.v1.Finance.GetWithdrawal:input_type -> finance.v1.GetWithdrawalRequest
	8,  // 14: finance.v1.Finance.ListWithdrawals:input_type -> finance.v1.ListWithdrawalsRequest
	11, // 15: finance.v1.Finance.ListIncomeLogs:input_type -> finance.v1.ListIncomeLogsRequest
	14, // 16: finance.v1.Finance.ListBalanceLogs:input_type -> finance.v1.ListBalanceLogsRequest
	16, // 17: finance.v1.Finance.CheckIn:input_type -> finance.v1.CheckInRequest
	19, // 18: finance.v1.Finance.GetUserBalance:input_type -> finance.v1.GetUserBalanceRequest
	0,  // 19: finance.v1.Finance.Recharge:output_type -> finance.v1.RechargeInfo
	0,  // 20: finance.v1.Finance.GetRecharge:output_type -> finance.v1.RechargeInfo
	4,  // 21: finance.v1.Finance.ListRecharges:output_type -> finance.v1.ListRechargesResponse
	5,  // 22: finance.v1.Finance.Withdraw:output_type -> finance.v1.WithdrawalInfo
	5,  // 23: finance.v1.Finance.GetWithdrawal:output_type -> finance.v1.WithdrawalInfo
	9,  // 24: finance.v1.Finance.ListWithdrawals:output_type -> finance.v1.ListWithdrawalsResponse
	12, // 25: finance.v1.Finance.ListIncomeLogs:output_type -> finance.v1.ListIncomeLogsResponse
	15, // 26: finance.v1.Finance.ListBalanceLogs:output_type -> finance.v1.ListBalanceLogsResponse
	17, // 27: finance.v1.Finance.CheckIn:output_type -> finance.v1.CheckInResponse
	18, // 28: finance.v1.Finance.GetUserBalance:output_type -> finance.v1.UserBalanceInfo
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_finance_v1_finance_proto_init() }
func file_finance_v1_finance_proto_init() {
	if File_finance_v1_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finance_v1_finance_proto_rawDesc), len(file_finance_v1_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finance_v1_finance_proto_goTypes,
		DependencyIndexes: file_finance_v1_finance_proto_depIdxs,
		MessageInfos:      file_finance_v1_finance_proto_msgTypes,
	}.Build()
	File_finance_v1_finance_proto = out.File
	file_finance_v1_finance_proto_goTypes = nil
	file_finance_v1_finance_proto_depIdxs = nil
}
