// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"mail/internal/biz"
	"mail/internal/conf"
	"mail/internal/data"
	"mail/internal/server"
	"mail/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, email *conf.Email, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	emailRepo := data.NewEmailRepo(dataData, logger)
	smtpConfig := newSMTPConfig(email)
	smtpSender := biz.NewSMTPSender(smtpConfig, logger)
	emailUsecase := biz.NewEmailUsecase(emailRepo, smtpSender, smtpConfig, logger)
	mailService := service.NewMailService(emailUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, mailService, logger)
	httpServer := server.NewHTTPServer(confServer, mailService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
