// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"admin/internal/biz"
	"admin/internal/conf"
	"admin/internal/data"
	"admin/internal/server"
	"admin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwtConf *conf.Jwt, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	adminRepo := data.NewAdminRepo(dataData, logger)
	menuRepo := data.NewMenuRepo(dataData, logger)
	roleRepo := data.NewRoleRepo(dataData, logger)
	adminRoleRepo := data.NewAdminRoleRepo(dataData, logger)
	adminLogRepo := data.NewAdminLogRepo(dataData, logger)
	adminUsecase := biz.NewAdminUsecase(adminRepo, roleRepo, adminRoleRepo, logger)
	menuUsecase := biz.NewMenuUsecase(menuRepo, logger)
	roleUsecase := biz.NewRoleUsecase(roleRepo, menuRepo, adminRoleRepo, logger)
	adminLogUsecase := biz.NewAdminLogUsecase(adminLogRepo, logger)
	jwtManager := service.NewJWTManagerProvider(jwtConf)
	adminService := service.NewAdminService(adminUsecase, menuUsecase, roleUsecase, adminLogUsecase, jwtManager, logger)
	grpcServer := server.NewGRPCServer(confServer, adminService, jwtManager, logger)
	httpServer := server.NewHTTPServer(confServer, adminService, jwtManager, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
