// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v7.34.1
// source: content/v1/content.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationContentCreateBanner = "/content.v1.Content/CreateBanner"
const OperationContentCreateNews = "/content.v1.Content/CreateNews"
const OperationContentDeleteBanner = "/content.v1.Content/DeleteBanner"
const OperationContentDeleteNews = "/content.v1.Content/DeleteNews"
const OperationContentGetBanner = "/content.v1.Content/GetBanner"
const OperationContentGetNews = "/content.v1.Content/GetNews"
const OperationContentListBanners = "/content.v1.Content/ListBanners"
const OperationContentListNews = "/content.v1.Content/ListNews"
const OperationContentRecordClick = "/content.v1.Content/RecordClick"
const OperationContentUpdateBanner = "/content.v1.Content/UpdateBanner"
const OperationContentUpdateNews = "/content.v1.Content/UpdateNews"

type ContentHTTPServer interface {
	CreateBanner(context.Context, *CreateBannerRequest) (*BannerInfo, error)
	CreateNews(context.Context, *CreateNewsRequest) (*NewsInfo, error)
	DeleteBanner(context.Context, *DeleteBannerRequest) (*DeleteBannerResponse, error)
	DeleteNews(context.Context, *DeleteNewsRequest) (*DeleteNewsResponse, error)
	GetBanner(context.Context, *GetBannerRequest) (*BannerInfo, error)
	GetNews(context.Context, *GetNewsRequest) (*NewsInfo, error)
	ListBanners(context.Context, *ListBannersRequest) (*ListBannersResponse, error)
	ListNews(context.Context, *ListNewsRequest) (*ListNewsResponse, error)
	RecordClick(context.Context, *RecordClickRequest) (*RecordClickResponse, error)
	UpdateBanner(context.Context, *UpdateBannerRequest) (*BannerInfo, error)
	UpdateNews(context.Context, *UpdateNewsRequest) (*NewsInfo, error)
}

func RegisterContentHTTPServer(s *http.Server, srv ContentHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/content/news", _Content_ListNews0_HTTP_Handler(srv))
	r.GET("/api/v1/content/news/{id}", _Content_GetNews0_HTTP_Handler(srv))
	r.POST("/api/v1/content/news", _Content_CreateNews0_HTTP_Handler(srv))
	r.PUT("/api/v1/content/news/{id}", _Content_UpdateNews0_HTTP_Handler(srv))
	r.DELETE("/api/v1/content/news/{id}", _Content_DeleteNews0_HTTP_Handler(srv))
	r.GET("/api/v1/content/banners", _Content_ListBanners0_HTTP_Handler(srv))
	r.GET("/api/v1/content/banners/{id}", _Content_GetBanner0_HTTP_Handler(srv))
	r.POST("/api/v1/content/banners", _Content_CreateBanner0_HTTP_Handler(srv))
	r.PUT("/api/v1/content/banners/{id}", _Content_UpdateBanner0_HTTP_Handler(srv))
	r.DELETE("/api/v1/content/banners/{id}", _Content_DeleteBanner0_HTTP_Handler(srv))
	r.POST("/api/v1/content/banners/{banner_id}/click", _Content_RecordClick0_HTTP_Handler(srv))
}

func _Content_ListNews0_HTTP_Handler(srv ContentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNewsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentListNews)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNews(ctx, req.(*ListNewsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNewsResponse)
		return ctx.Result(200, reply)
	}
}

func _Content_GetNews0_HTTP_Handler(srv ContentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNewsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentGetNews)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNews(ctx, req.(*GetNewsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NewsInfo)
		return ctx.Result(200, reply)
	}
}

func _Content_CreateNews0_HTTP_Handler(srv ContentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateNewsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentCreateNews)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNews(ctx, req.(*CreateNewsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NewsInfo)
		return ctx.Result(200, reply)
	}
}

func _Content_UpdateNews0_HTTP_Handler(srv ContentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateNewsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentUpdateNews)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateNews(ctx, req.(*UpdateNewsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NewsInfo)
		return ctx.Result(200, reply)
	}
}

func _Content_DeleteNews0_HTTP_Handler(srv ContentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteNewsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentDeleteNews)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteNews(ctx, req.(*DeleteNewsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteNewsResponse)
		return ctx.Result(200, reply)
	}
}

func _Content_ListBanners0_HTTP_Handler(srv ContentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBannersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentListBanners)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBanners(ctx, req.(*ListBannersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBannersResponse)
		return ctx.Result(200, reply)
	}
}

func _Content_GetBanner0_HTTP_Handler(srv ContentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBannerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentGetBanner)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBanner(ctx, req.(*GetBannerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BannerInfo)
		return ctx.Result(200, reply)
	}
}

func _Content_CreateBanner0_HTTP_Handler(srv ContentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateBannerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentCreateBanner)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateBanner(ctx, req.(*CreateBannerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BannerInfo)
		return ctx.Result(200, reply)
	}
}

func _Content_UpdateBanner0_HTTP_Handler(srv ContentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateBannerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentUpdateBanner)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBanner(ctx, req.(*UpdateBannerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BannerInfo)
		return ctx.Result(200, reply)
	}
}

func _Content_DeleteBanner0_HTTP_Handler(srv ContentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteBannerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentDeleteBanner)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteBanner(ctx, req.(*DeleteBannerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteBannerResponse)
		return ctx.Result(200, reply)
	}
}

func _Content_RecordClick0_HTTP_Handler(srv ContentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RecordClickRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationContentRecordClick)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RecordClick(ctx, req.(*RecordClickRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RecordClickResponse)
		return ctx.Result(200, reply)
	}
}

type ContentHTTPClient interface {
	CreateBanner(ctx context.Context, req *CreateBannerRequest, opts ...http.CallOption) (rsp *BannerInfo, err error)
	CreateNews(ctx context.Context, req *CreateNewsRequest, opts ...http.CallOption) (rsp *NewsInfo, err error)
	DeleteBanner(ctx context.Context, req *DeleteBannerRequest, opts ...http.CallOption) (rsp *DeleteBannerResponse, err error)
	DeleteNews(ctx context.Context, req *DeleteNewsRequest, opts ...http.CallOption) (rsp *DeleteNewsResponse, err error)
	GetBanner(ctx context.Context, req *GetBannerRequest, opts ...http.CallOption) (rsp *BannerInfo, err error)
	GetNews(ctx context.Context, req *GetNewsRequest, opts ...http.CallOption) (rsp *NewsInfo, err error)
	ListBanners(ctx context.Context, req *ListBannersRequest, opts ...http.CallOption) (rsp *ListBannersResponse, err error)
	ListNews(ctx context.Context, req *ListNewsRequest, opts ...http.CallOption) (rsp *ListNewsResponse, err error)
	RecordClick(ctx context.Context, req *RecordClickRequest, opts ...http.CallOption) (rsp *RecordClickResponse, err error)
	UpdateBanner(ctx context.Context, req *UpdateBannerRequest, opts ...http.CallOption) (rsp *BannerInfo, err error)
	UpdateNews(ctx context.Context, req *UpdateNewsRequest, opts ...http.CallOption) (rsp *NewsInfo, err error)
}

type ContentHTTPClientImpl struct {
	cc *http.Client
}

func NewContentHTTPClient(client *http.Client) ContentHTTPClient {
	return &ContentHTTPClientImpl{client}
}

func (c *ContentHTTPClientImpl) CreateBanner(ctx context.Context, in *CreateBannerRequest, opts ...http.CallOption) (*BannerInfo, error) {
	var out BannerInfo
	pattern := "/api/v1/content/banners"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationContentCreateBanner))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentHTTPClientImpl) CreateNews(ctx context.Context, in *CreateNewsRequest, opts ...http.CallOption) (*NewsInfo, error) {
	var out NewsInfo
	pattern := "/api/v1/content/news"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationContentCreateNews))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentHTTPClientImpl) DeleteBanner(ctx context.Context, in *DeleteBannerRequest, opts ...http.CallOption) (*DeleteBannerResponse, error) {
	var out DeleteBannerResponse
	pattern := "/api/v1/content/banners/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContentDeleteBanner))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentHTTPClientImpl) DeleteNews(ctx context.Context, in *DeleteNewsRequest, opts ...http.CallOption) (*DeleteNewsResponse, error) {
	var out DeleteNewsResponse
	pattern := "/api/v1/content/news/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContentDeleteNews))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentHTTPClientImpl) GetBanner(ctx context.Context, in *GetBannerRequest, opts ...http.CallOption) (*BannerInfo, error) {
	var out BannerInfo
	pattern := "/api/v1/content/banners/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContentGetBanner))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentHTTPClientImpl) GetNews(ctx context.Context, in *GetNewsRequest, opts ...http.CallOption) (*NewsInfo, error) {
	var out NewsInfo
	pattern := "/api/v1/content/news/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContentGetNews))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentHTTPClientImpl) ListBanners(ctx context.Context, in *ListBannersRequest, opts ...http.CallOption) (*ListBannersResponse, error) {
	var out ListBannersResponse
	pattern := "/api/v1/content/banners"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContentListBanners))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentHTTPClientImpl) ListNews(ctx context.Context, in *ListNewsRequest, opts ...http.CallOption) (*ListNewsResponse, error) {
	var out ListNewsResponse
	pattern := "/api/v1/content/news"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationContentListNews))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentHTTPClientImpl) RecordClick(ctx context.Context, in *RecordClickRequest, opts ...http.CallOption) (*RecordClickResponse, error) {
	var out RecordClickResponse
	pattern := "/api/v1/content/banners/{banner_id}/click"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationContentRecordClick))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentHTTPClientImpl) UpdateBanner(ctx context.Context, in *UpdateBannerRequest, opts ...http.CallOption) (*BannerInfo, error) {
	var out BannerInfo
	pattern := "/api/v1/content/banners/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationContentUpdateBanner))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ContentHTTPClientImpl) UpdateNews(ctx context.Context, in *UpdateNewsRequest, opts ...http.CallOption) (*NewsInfo, error) {
	var out NewsInfo
	pattern := "/api/v1/content/news/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationContentUpdateNews))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
