// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: report/v1/report.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 订单报表请求
type GetOrderReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Page          uint32                 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReportRequest) Reset() {
	*x = GetOrderReportRequest{}
	mi := &file_report_v1_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReportRequest) ProtoMessage() {}

func (x *GetOrderReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReportRequest.ProtoReflect.Descriptor instead.
func (*GetOrderReportRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderReportRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetOrderReportRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetOrderReportRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetOrderReportRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrderReportRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 订单报表响应
type OrderReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OrderReportItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	TotalOrders   uint32                 `protobuf:"varint,4,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderReportResponse) Reset() {
	*x = OrderReportResponse{}
	mi := &file_report_v1_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReportResponse) ProtoMessage() {}

func (x *OrderReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReportResponse.ProtoReflect.Descriptor instead.
func (*OrderReportResponse) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{1}
}

func (x *OrderReportResponse) GetItems() []*OrderReportItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderReportResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderReportResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderReportResponse) GetTotalOrders() uint32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

// 订单报表项
type OrderReportItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ProductName   string                 `protobuf:"bytes,5,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Amount        float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderReportItem) Reset() {
	*x = OrderReportItem{}
	mi := &file_report_v1_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReportItem) ProtoMessage() {}

func (x *OrderReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReportItem.ProtoReflect.Descriptor instead.
func (*OrderReportItem) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{2}
}

func (x *OrderReportItem) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderReportItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderReportItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderReportItem) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *OrderReportItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderReportItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderReportItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderReportItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 用户报表请求
type GetUserReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReportRequest) Reset() {
	*x = GetUserReportRequest{}
	mi := &file_report_v1_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReportRequest) ProtoMessage() {}

func (x *GetUserReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReportRequest.ProtoReflect.Descriptor instead.
func (*GetUserReportRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserReportRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetUserReportRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetUserReportRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserReportRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 用户报表响应
type UserReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserReportItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	TotalUsers    uint32                 `protobuf:"varint,3,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	ActiveUsers   uint32                 `protobuf:"varint,4,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReportResponse) Reset() {
	*x = UserReportResponse{}
	mi := &file_report_v1_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReportResponse) ProtoMessage() {}

func (x *UserReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReportResponse.ProtoReflect.Descriptor instead.
func (*UserReportResponse) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{4}
}

func (x *UserReportResponse) GetItems() []*UserReportItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UserReportResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserReportResponse) GetTotalUsers() uint32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *UserReportResponse) GetActiveUsers() uint32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

// 用户报表项
type UserReportItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	OrderCount    uint32                 `protobuf:"varint,5,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastLogin     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReportItem) Reset() {
	*x = UserReportItem{}
	mi := &file_report_v1_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReportItem) ProtoMessage() {}

func (x *UserReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReportItem.ProtoReflect.Descriptor instead.
func (*UserReportItem) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{5}
}

func (x *UserReportItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserReportItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserReportItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserReportItem) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserReportItem) GetOrderCount() uint32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *UserReportItem) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *UserReportItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserReportItem) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

// 销售报表请求
type GetSalesReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	GroupBy       string                 `protobuf:"bytes,3,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"` // day, week, month
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesReportRequest) Reset() {
	*x = GetSalesReportRequest{}
	mi := &file_report_v1_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesReportRequest) ProtoMessage() {}

func (x *GetSalesReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesReportRequest.ProtoReflect.Descriptor instead.
func (*GetSalesReportRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{6}
}

func (x *GetSalesReportRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetSalesReportRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetSalesReportRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

// 销售报表响应
type SalesReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SalesReportItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalSales    float64                `protobuf:"fixed64,2,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	TotalOrders   uint32                 `protobuf:"varint,3,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	AvgOrderValue float64                `protobuf:"fixed64,4,opt,name=avg_order_value,json=avgOrderValue,proto3" json:"avg_order_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalesReportResponse) Reset() {
	*x = SalesReportResponse{}
	mi := &file_report_v1_report_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesReportResponse) ProtoMessage() {}

func (x *SalesReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesReportResponse.ProtoReflect.Descriptor instead.
func (*SalesReportResponse) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{7}
}

func (x *SalesReportResponse) GetItems() []*SalesReportItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SalesReportResponse) GetTotalSales() float64 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

func (x *SalesReportResponse) GetTotalOrders() uint32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *SalesReportResponse) GetAvgOrderValue() float64 {
	if x != nil {
		return x.AvgOrderValue
	}
	return 0
}

// 销售报表项
type SalesReportItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"` // 日期/周/月
	SalesAmount   float64                `protobuf:"fixed64,2,opt,name=sales_amount,json=salesAmount,proto3" json:"sales_amount,omitempty"`
	OrderCount    uint32                 `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	ProductCount  uint32                 `protobuf:"varint,4,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalesReportItem) Reset() {
	*x = SalesReportItem{}
	mi := &file_report_v1_report_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesReportItem) ProtoMessage() {}

func (x *SalesReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesReportItem.ProtoReflect.Descriptor instead.
func (*SalesReportItem) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{8}
}

func (x *SalesReportItem) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *SalesReportItem) GetSalesAmount() float64 {
	if x != nil {
		return x.SalesAmount
	}
	return 0
}

func (x *SalesReportItem) GetOrderCount() uint32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *SalesReportItem) GetProductCount() uint32 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

// 商品报表请求
type GetProductReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReportRequest) Reset() {
	*x = GetProductReportRequest{}
	mi := &file_report_v1_report_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReportRequest) ProtoMessage() {}

func (x *GetProductReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReportRequest.ProtoReflect.Descriptor instead.
func (*GetProductReportRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{9}
}

func (x *GetProductReportRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetProductReportRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetProductReportRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetProductReportRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 商品报表响应
type ProductReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProductReportItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductReportResponse) Reset() {
	*x = ProductReportResponse{}
	mi := &file_report_v1_report_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductReportResponse) ProtoMessage() {}

func (x *ProductReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductReportResponse.ProtoReflect.Descriptor instead.
func (*ProductReportResponse) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{10}
}

func (x *ProductReportResponse) GetItems() []*ProductReportItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ProductReportResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 商品报表项
type ProductReportItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	SalesCount    uint32                 `protobuf:"varint,3,opt,name=sales_count,json=salesCount,proto3" json:"sales_count,omitempty"`
	SalesAmount   float64                `protobuf:"fixed64,4,opt,name=sales_amount,json=salesAmount,proto3" json:"sales_amount,omitempty"`
	StockQuantity uint32                 `protobuf:"varint,5,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductReportItem) Reset() {
	*x = ProductReportItem{}
	mi := &file_report_v1_report_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductReportItem) ProtoMessage() {}

func (x *ProductReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductReportItem.ProtoReflect.Descriptor instead.
func (*ProductReportItem) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{11}
}

func (x *ProductReportItem) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductReportItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductReportItem) GetSalesCount() uint32 {
	if x != nil {
		return x.SalesCount
	}
	return 0
}

func (x *ProductReportItem) GetSalesAmount() float64 {
	if x != nil {
		return x.SalesAmount
	}
	return 0
}

func (x *ProductReportItem) GetStockQuantity() uint32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

// 导出订单报表请求
type ExportOrderReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"` // xlsx, csv
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportOrderReportRequest) Reset() {
	*x = ExportOrderReportRequest{}
	mi := &file_report_v1_report_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportOrderReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportOrderReportRequest) ProtoMessage() {}

func (x *ExportOrderReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportOrderReportRequest.ProtoReflect.Descriptor instead.
func (*ExportOrderReportRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{12}
}

func (x *ExportOrderReportRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ExportOrderReportRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *ExportOrderReportRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ExportOrderReportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// 导出用户报表请求
type ExportUserReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportUserReportRequest) Reset() {
	*x = ExportUserReportRequest{}
	mi := &file_report_v1_report_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportUserReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportUserReportRequest) ProtoMessage() {}

func (x *ExportUserReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportUserReportRequest.ProtoReflect.Descriptor instead.
func (*ExportUserReportRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{13}
}

func (x *ExportUserReportRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ExportUserReportRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *ExportUserReportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// 导出销售报表请求
type ExportSalesReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	GroupBy       string                 `protobuf:"bytes,3,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSalesReportRequest) Reset() {
	*x = ExportSalesReportRequest{}
	mi := &file_report_v1_report_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSalesReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSalesReportRequest) ProtoMessage() {}

func (x *ExportSalesReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSalesReportRequest.ProtoReflect.Descriptor instead.
func (*ExportSalesReportRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{14}
}

func (x *ExportSalesReportRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ExportSalesReportRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *ExportSalesReportRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

func (x *ExportSalesReportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// 导出商品报表请求
type ExportProductReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportProductReportRequest) Reset() {
	*x = ExportProductReportRequest{}
	mi := &file_report_v1_report_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportProductReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportProductReportRequest) ProtoMessage() {}

func (x *ExportProductReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportProductReportRequest.ProtoReflect.Descriptor instead.
func (*ExportProductReportRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{15}
}

func (x *ExportProductReportRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ExportProductReportRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *ExportProductReportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// 导出报表响应
type ExportReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileData      []byte                 `protobuf:"bytes,4,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"` // 直接返回文件数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReportResponse) Reset() {
	*x = ExportReportResponse{}
	mi := &file_report_v1_report_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReportResponse) ProtoMessage() {}

func (x *ExportReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReportResponse.ProtoReflect.Descriptor instead.
func (*ExportReportResponse) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{16}
}

func (x *ExportReportResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ExportReportResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ExportReportResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ExportReportResponse) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

var File_report_v1_report_proto protoreflect.FileDescriptor

const file_report_v1_report_proto_rawDesc = "" +
	"\n" +
	"\x16report/v1/report.proto\x12\treport.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xd2\x01\n" +
	"\x15GetOrderReportRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x04 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\rR\bpageSize\"\xa3\x01\n" +
	"\x13OrderReportResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.report.v1.OrderReportItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\x12!\n" +
	"\ftotal_orders\x18\x04 \x01(\rR\vtotalOrders\"\x8b\x02\n" +
	"\x0fOrderReportItem\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\x12!\n" +
	"\fproduct_name\x18\x05 \x01(\tR\vproductName\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb9\x01\n" +
	"\x14GetUserReportRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"\x9f\x01\n" +
	"\x12UserReportResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.report.v1.UserReportItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x1f\n" +
	"\vtotal_users\x18\x03 \x01(\rR\n" +
	"totalUsers\x12!\n" +
	"\factive_users\x18\x04 \x01(\rR\vactiveUsers\"\xab\x02\n" +
	"\x0eUserReportItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1f\n" +
	"\vorder_count\x18\x05 \x01(\rR\n" +
	"orderCount\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\x01R\vtotalAmount\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"last_login\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\"\xa4\x01\n" +
	"\x15GetSalesReportRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x19\n" +
	"\bgroup_by\x18\x03 \x01(\tR\agroupBy\"\xb3\x01\n" +
	"\x13SalesReportResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.report.v1.SalesReportItemR\x05items\x12\x1f\n" +
	"\vtotal_sales\x18\x02 \x01(\x01R\n" +
	"totalSales\x12!\n" +
	"\ftotal_orders\x18\x03 \x01(\rR\vtotalOrders\x12&\n" +
	"\x0favg_order_value\x18\x04 \x01(\x01R\ravgOrderValue\"\x92\x01\n" +
	"\x0fSalesReportItem\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12!\n" +
	"\fsales_amount\x18\x02 \x01(\x01R\vsalesAmount\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\rR\n" +
	"orderCount\x12#\n" +
	"\rproduct_count\x18\x04 \x01(\rR\fproductCount\"\xbc\x01\n" +
	"\x17GetProductReportRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"a\n" +
	"\x15ProductReportResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.report.v1.ProductReportItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"\xc0\x01\n" +
	"\x11ProductReportItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1f\n" +
	"\vsales_count\x18\x03 \x01(\rR\n" +
	"salesCount\x12!\n" +
	"\fsales_amount\x18\x04 \x01(\x01R\vsalesAmount\x12%\n" +
	"\x0estock_quantity\x18\x05 \x01(\rR\rstockQuantity\"\xbc\x01\n" +
	"\x18ExportOrderReportRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"\xa3\x01\n" +
	"\x17ExportUserReportRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"\xbf\x01\n" +
	"\x18ExportSalesReportRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x19\n" +
	"\bgroup_by\x18\x03 \x01(\tR\agroupBy\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"\xa6\x01\n" +
	"\x1aExportProductReportRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"\x90\x01\n" +
	"\x14ExportReportResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_data\x18\x04 \x01(\fR\bfileData2\xe7\a\n" +
	"\x06Report\x12r\n" +
	"\x0eGetOrderReport\x12 .report.v1.GetOrderReportRequest\x1a\x1e.report.v1.OrderReportResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/reports/orders\x12n\n" +
	"\rGetUserReport\x12\x1f.report.v1.GetUserReportRequest\x1a\x1d.report.v1.UserReportResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/reports/users\x12q\n" +
	"\x0eGetSalesReport\x12 .report.v1.GetSalesReportRequest\x1a\x1e.report.v1.SalesReportResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/reports/sales\x12z\n" +
	"\x10GetProductReport\x12\".report.v1.GetProductReportRequest\x1a .report.v1.ProductReportResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/reports/products\x12\x80\x01\n" +
	"\x11ExportOrderReport\x12#.report.v1.ExportOrderReportRequest\x1a\x1f.report.v1.ExportReportResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/reports/orders/export\x12}\n" +
	"\x10ExportUserReport\x12\".report.v1.ExportUserReportRequest\x1a\x1f.report.v1.ExportReportResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/reports/users/export\x12\x7f\n" +
	"\x11ExportSalesReport\x12#.report.v1.ExportSalesReportRequest\x1a\x1f.report.v1.ExportReportResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/reports/sales/export\x12\x86\x01\n" +
	"\x13ExportProductReport\x12%.report.v1.ExportProductReportRequest\x1a\x1f.report.v1.ExportReportResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/reports/products/exportB\x19Z\x17report/api/report/v1;v1b\x06proto3"

var (
	file_report_v1_report_proto_rawDescOnce sync.Once
	file_report_v1_report_proto_rawDescData []byte
)

func file_report_v1_report_proto_rawDescGZIP() []byte {
	file_report_v1_report_proto_rawDescOnce.Do(func() {
		file_report_v1_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_v1_report_proto_rawDesc), len(file_report_v1_report_proto_rawDesc)))
	})
	return file_report_v1_report_proto_rawDescData
}

var file_report_v1_report_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_report_v1_report_proto_goTypes = []any{
	(*GetOrderReportRequest)(nil),      // 0: report.v1.GetOrderReportRequest
	(*OrderReportResponse)(nil),        // 1: report.v1.OrderReportResponse
	(*OrderReportItem)(nil),            // 2: report.v1.OrderReportItem
	(*GetUserReportRequest)(nil),       // 3: report.v1.GetUserReportRequest
	(*UserReportResponse)(nil),         // 4: report.v1.UserReportResponse
	(*UserReportItem)(nil),             // 5: report.v1.UserReportItem
	(*GetSalesReportRequest)(nil),      // 6: report.v1.GetSalesReportRequest
	(*SalesReportResponse)(nil),        // 7: report.v1.SalesReportResponse
	(*SalesReportItem)(nil),            // 8: report.v1.SalesReportItem
	(*GetProductReportRequest)(nil),    // 9: report.v1.GetProductReportRequest
	(*ProductReportResponse)(nil),      // 10: report.v1.ProductReportResponse
	(*ProductReportItem)(nil),          // 11: report.v1.ProductReportItem
	(*ExportOrderReportRequest)(nil),   // 12: report.v1.ExportOrderReportRequest
	(*ExportUserReportRequest)(nil),    // 13: report.v1.ExportUserReportRequest
	(*ExportSalesReportRequest)(nil),   // 14: report.v1.ExportSalesReportRequest
	(*ExportProductReportRequest)(nil), // 15: report.v1.ExportProductReportRequest
	(*ExportReportResponse)(nil),       // 16: report.v1.ExportReportResponse
	(*timestamppb.Timestamp)(nil),      // 17: google.protobuf.Timestamp
}
var file_report_v1_report_proto_depIdxs = []int32{
	17, // 0: report.v1.GetOrderReportRequest.start_date:type_name -> google.protobuf.Timestamp
	17, // 1: report.v1.GetOrderReportRequest.end_date:type_name -> google.protobuf.Timestamp
	2,  // 2: report.v1.OrderReportResponse.items:type_name -> report.v1.OrderReportItem
	17, // 3: report.v1.OrderReportItem.created_at:type_name -> google.protobuf.Timestamp
	17, // 4: report.v1.GetUserReportRequest.start_date:type_name -> google.protobuf.Timestamp
	17, // 5: report.v1.GetUserReportRequest.end_date:type_name -> google.protobuf.Timestamp
	5,  // 6: report.v1.UserReportResponse.items:type_name -> report.v1.UserReportItem
	17, // 7: report.v1.UserReportItem.created_at:type_name -> google.protobuf.Timestamp
	17, // 8: report.v1.UserReportItem.last_login:type_name -> google.protobuf.Timestamp
	17, // 9: report.v1.GetSalesReportRequest.start_date:type_name -> google.protobuf.Timestamp
	17, // 10: report.v1.GetSalesReportRequest.end_date:type_name -> google.protobuf.Timestamp
	8,  // 11: report.v1.SalesReportResponse.items:type_name -> report.v1.SalesReportItem
	17, // 12: report.v1.GetProductReportRequest.start_date:type_name -> google.protobuf.Timestamp
	17, // 13: report.v1.GetProductReportRequest.end_date:type_name -> google.protobuf.Timestamp
	11, // 14: report.v1.ProductReportResponse.items:type_name -> report.v1.ProductReportItem
	17, // 15: report.v1.ExportOrderReportRequest.start_date:type_name -> google.protobuf.Timestamp
	17, // 16: report.v1.ExportOrderReportRequest.end_date:type_name -> google.protobuf.Timestamp
	17, // 17: report.v1.ExportUserReportRequest.start_date:type_name -> google.protobuf.Timestamp
	17, // 18: report.v1.ExportUserReportRequest.end_date:type_name -> google.protobuf.Timestamp
	17, // 19: report.v1.ExportSalesReportRequest.start_date:type_name -> google.protobuf.Timestamp
	17, // 20: report.v1.ExportSalesReportRequest.end_date:type_name -> google.protobuf.Timestamp
	17, // 21: report.v1.ExportProductReportRequest.start_date:type_name -> google.protobuf.Timestamp
	17, // 22: report.v1.ExportProductReportRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 23: report.v1.Report.GetOrderReport:input_type -> report.v1.GetOrderReportRequest
	3,  // 24: report.v1.Report.GetUserReport:input_type -> report.v1.GetUserReportRequest
	6,  // 25: report.v1.Report.GetSalesReport:input_type -> report.v1.GetSalesReportRequest
	9,  // 26: report.v1.Report.GetProductReport:input_type -> report.v1.GetProductReportRequest
	12, // 27: report.v1.Report.ExportOrderReport:input_type -> report.v1.ExportOrderReportRequest
	13, // 28: report.v1.Report.ExportUserReport:input_type -> report.v1.ExportUserReportRequest
	14, // 29: report.v1.Report.ExportSalesReport:input_type -> report.v1.ExportSalesReportRequest
	15, // 30: report.v1.Report.ExportProductReport:input_type -> report.v1.ExportProductReportRequest
	1,  // 31: report.v1.Report.GetOrderReport:output_type -> report.v1.OrderReportResponse
	4,  // 32: report.v1.Report.GetUserReport:output_type -> report.v1.UserReportResponse
	7,  // 33: report.v1.Report.GetSalesReport:output_type -> report.v1.SalesReportResponse
	10, // 34: report.v1.Report.GetProductReport:output_type -> report.v1.ProductReportResponse
	16, // 35: report.v1.Report.ExportOrderReport:output_type -> report.v1.ExportReportResponse
	16, // 36: report.v1.Report.ExportUserReport:output_type -> report.v1.ExportReportResponse
	16, // 37: report.v1.Report.ExportSalesReport:output_type -> report.v1.ExportReportResponse
	16, // 38: report.v1.Report.ExportProductReport:output_type -> report.v1.ExportReportResponse
	31, // [31:39] is the sub-list for method output_type
	23, // [23:31] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_report_v1_report_proto_init() }
func file_report_v1_report_proto_init() {
	if File_report_v1_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_v1_report_proto_rawDesc), len(file_report_v1_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_v1_report_proto_goTypes,
		DependencyIndexes: file_report_v1_report_proto_depIdxs,
		MessageInfos:      file_report_v1_report_proto_msgTypes,
	}.Build()
	File_report_v1_report_proto = out.File
	file_report_v1_report_proto_goTypes = nil
	file_report_v1_report_proto_depIdxs = nil
}
