// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v7.34.1
// source: report/v1/report.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationReportExportOrderReport = "/report.v1.Report/ExportOrderReport"
const OperationReportExportProductReport = "/report.v1.Report/ExportProductReport"
const OperationReportExportSalesReport = "/report.v1.Report/ExportSalesReport"
const OperationReportExportUserReport = "/report.v1.Report/ExportUserReport"
const OperationReportGetOrderReport = "/report.v1.Report/GetOrderReport"
const OperationReportGetProductReport = "/report.v1.Report/GetProductReport"
const OperationReportGetSalesReport = "/report.v1.Report/GetSalesReport"
const OperationReportGetUserReport = "/report.v1.Report/GetUserReport"

type ReportHTTPServer interface {
	// ExportOrderReport 导出订单报表到Excel
	ExportOrderReport(context.Context, *ExportOrderReportRequest) (*ExportReportResponse, error)
	// ExportProductReport 导出商品报表到Excel
	ExportProductReport(context.Context, *ExportProductReportRequest) (*ExportReportResponse, error)
	// ExportSalesReport 导出销售报表到Excel
	ExportSalesReport(context.Context, *ExportSalesReportRequest) (*ExportReportResponse, error)
	// ExportUserReport 导出用户报表到Excel
	ExportUserReport(context.Context, *ExportUserReportRequest) (*ExportReportResponse, error)
	// GetOrderReport 订单报表
	GetOrderReport(context.Context, *GetOrderReportRequest) (*OrderReportResponse, error)
	// GetProductReport 商品报表
	GetProductReport(context.Context, *GetProductReportRequest) (*ProductReportResponse, error)
	// GetSalesReport 销售报表
	GetSalesReport(context.Context, *GetSalesReportRequest) (*SalesReportResponse, error)
	// GetUserReport 用户报表
	GetUserReport(context.Context, *GetUserReportRequest) (*UserReportResponse, error)
}

func RegisterReportHTTPServer(s *http.Server, srv ReportHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/reports/orders", _Report_GetOrderReport0_HTTP_Handler(srv))
	r.GET("/api/v1/reports/users", _Report_GetUserReport0_HTTP_Handler(srv))
	r.GET("/api/v1/reports/sales", _Report_GetSalesReport0_HTTP_Handler(srv))
	r.GET("/api/v1/reports/products", _Report_GetProductReport0_HTTP_Handler(srv))
	r.GET("/api/v1/reports/orders/export", _Report_ExportOrderReport0_HTTP_Handler(srv))
	r.GET("/api/v1/reports/users/export", _Report_ExportUserReport0_HTTP_Handler(srv))
	r.GET("/api/v1/reports/sales/export", _Report_ExportSalesReport0_HTTP_Handler(srv))
	r.GET("/api/v1/reports/products/export", _Report_ExportProductReport0_HTTP_Handler(srv))
}

func _Report_GetOrderReport0_HTTP_Handler(srv ReportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReportGetOrderReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrderReport(ctx, req.(*GetOrderReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderReportResponse)
		return ctx.Result(200, reply)
	}
}

func _Report_GetUserReport0_HTTP_Handler(srv ReportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReportGetUserReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserReport(ctx, req.(*GetUserReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserReportResponse)
		return ctx.Result(200, reply)
	}
}

func _Report_GetSalesReport0_HTTP_Handler(srv ReportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSalesReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReportGetSalesReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSalesReport(ctx, req.(*GetSalesReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SalesReportResponse)
		return ctx.Result(200, reply)
	}
}

func _Report_GetProductReport0_HTTP_Handler(srv ReportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProductReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReportGetProductReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProductReport(ctx, req.(*GetProductReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProductReportResponse)
		return ctx.Result(200, reply)
	}
}

func _Report_ExportOrderReport0_HTTP_Handler(srv ReportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExportOrderReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReportExportOrderReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExportOrderReport(ctx, req.(*ExportOrderReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExportReportResponse)
		return ctx.Result(200, reply)
	}
}

func _Report_ExportUserReport0_HTTP_Handler(srv ReportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExportUserReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReportExportUserReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExportUserReport(ctx, req.(*ExportUserReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExportReportResponse)
		return ctx.Result(200, reply)
	}
}

func _Report_ExportSalesReport0_HTTP_Handler(srv ReportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExportSalesReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReportExportSalesReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExportSalesReport(ctx, req.(*ExportSalesReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExportReportResponse)
		return ctx.Result(200, reply)
	}
}

func _Report_ExportProductReport0_HTTP_Handler(srv ReportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExportProductReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReportExportProductReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExportProductReport(ctx, req.(*ExportProductReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExportReportResponse)
		return ctx.Result(200, reply)
	}
}

type ReportHTTPClient interface {
	ExportOrderReport(ctx context.Context, req *ExportOrderReportRequest, opts ...http.CallOption) (rsp *ExportReportResponse, err error)
	ExportProductReport(ctx context.Context, req *ExportProductReportRequest, opts ...http.CallOption) (rsp *ExportReportResponse, err error)
	ExportSalesReport(ctx context.Context, req *ExportSalesReportRequest, opts ...http.CallOption) (rsp *ExportReportResponse, err error)
	ExportUserReport(ctx context.Context, req *ExportUserReportRequest, opts ...http.CallOption) (rsp *ExportReportResponse, err error)
	GetOrderReport(ctx context.Context, req *GetOrderReportRequest, opts ...http.CallOption) (rsp *OrderReportResponse, err error)
	GetProductReport(ctx context.Context, req *GetProductReportRequest, opts ...http.CallOption) (rsp *ProductReportResponse, err error)
	GetSalesReport(ctx context.Context, req *GetSalesReportRequest, opts ...http.CallOption) (rsp *SalesReportResponse, err error)
	GetUserReport(ctx context.Context, req *GetUserReportRequest, opts ...http.CallOption) (rsp *UserReportResponse, err error)
}

type ReportHTTPClientImpl struct {
	cc *http.Client
}

func NewReportHTTPClient(client *http.Client) ReportHTTPClient {
	return &ReportHTTPClientImpl{client}
}

func (c *ReportHTTPClientImpl) ExportOrderReport(ctx context.Context, in *ExportOrderReportRequest, opts ...http.CallOption) (*ExportReportResponse, error) {
	var out ExportReportResponse
	pattern := "/api/v1/reports/orders/export"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReportExportOrderReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReportHTTPClientImpl) ExportProductReport(ctx context.Context, in *ExportProductReportRequest, opts ...http.CallOption) (*ExportReportResponse, error) {
	var out ExportReportResponse
	pattern := "/api/v1/reports/products/export"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReportExportProductReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReportHTTPClientImpl) ExportSalesReport(ctx context.Context, in *ExportSalesReportRequest, opts ...http.CallOption) (*ExportReportResponse, error) {
	var out ExportReportResponse
	pattern := "/api/v1/reports/sales/export"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReportExportSalesReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReportHTTPClientImpl) ExportUserReport(ctx context.Context, in *ExportUserReportRequest, opts ...http.CallOption) (*ExportReportResponse, error) {
	var out ExportReportResponse
	pattern := "/api/v1/reports/users/export"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReportExportUserReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReportHTTPClientImpl) GetOrderReport(ctx context.Context, in *GetOrderReportRequest, opts ...http.CallOption) (*OrderReportResponse, error) {
	var out OrderReportResponse
	pattern := "/api/v1/reports/orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReportGetOrderReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReportHTTPClientImpl) GetProductReport(ctx context.Context, in *GetProductReportRequest, opts ...http.CallOption) (*ProductReportResponse, error) {
	var out ProductReportResponse
	pattern := "/api/v1/reports/products"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReportGetProductReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReportHTTPClientImpl) GetSalesReport(ctx context.Context, in *GetSalesReportRequest, opts ...http.CallOption) (*SalesReportResponse, error) {
	var out SalesReportResponse
	pattern := "/api/v1/reports/sales"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReportGetSalesReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReportHTTPClientImpl) GetUserReport(ctx context.Context, in *GetUserReportRequest, opts ...http.CallOption) (*UserReportResponse, error) {
	var out UserReportResponse
	pattern := "/api/v1/reports/users"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReportGetUserReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
