// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: report/v1/report.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Report_GetOrderReport_FullMethodName      = "/report.v1.Report/GetOrderReport"
	Report_GetUserReport_FullMethodName       = "/report.v1.Report/GetUserReport"
	Report_GetSalesReport_FullMethodName      = "/report.v1.Report/GetSalesReport"
	Report_GetProductReport_FullMethodName    = "/report.v1.Report/GetProductReport"
	Report_ExportOrderReport_FullMethodName   = "/report.v1.Report/ExportOrderReport"
	Report_ExportUserReport_FullMethodName    = "/report.v1.Report/ExportUserReport"
	Report_ExportSalesReport_FullMethodName   = "/report.v1.Report/ExportSalesReport"
	Report_ExportProductReport_FullMethodName = "/report.v1.Report/ExportProductReport"
)

// ReportClient is the client API for Report service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportClient interface {
	// 订单报表
	GetOrderReport(ctx context.Context, in *GetOrderReportRequest, opts ...grpc.CallOption) (*OrderReportResponse, error)
	// 用户报表
	GetUserReport(ctx context.Context, in *GetUserReportRequest, opts ...grpc.CallOption) (*UserReportResponse, error)
	// 销售报表
	GetSalesReport(ctx context.Context, in *GetSalesReportRequest, opts ...grpc.CallOption) (*SalesReportResponse, error)
	// 商品报表
	GetProductReport(ctx context.Context, in *GetProductReportRequest, opts ...grpc.CallOption) (*ProductReportResponse, error)
	// 导出订单报表到Excel
	ExportOrderReport(ctx context.Context, in *ExportOrderReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error)
	// 导出用户报表到Excel
	ExportUserReport(ctx context.Context, in *ExportUserReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error)
	// 导出销售报表到Excel
	ExportSalesReport(ctx context.Context, in *ExportSalesReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error)
	// 导出商品报表到Excel
	ExportProductReport(ctx context.Context, in *ExportProductReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error)
}

type reportClient struct {
	cc grpc.ClientConnInterface
}

func NewReportClient(cc grpc.ClientConnInterface) ReportClient {
	return &reportClient{cc}
}

func (c *reportClient) GetOrderReport(ctx context.Context, in *GetOrderReportRequest, opts ...grpc.CallOption) (*OrderReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderReportResponse)
	err := c.cc.Invoke(ctx, Report_GetOrderReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) GetUserReport(ctx context.Context, in *GetUserReportRequest, opts ...grpc.CallOption) (*UserReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserReportResponse)
	err := c.cc.Invoke(ctx, Report_GetUserReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) GetSalesReport(ctx context.Context, in *GetSalesReportRequest, opts ...grpc.CallOption) (*SalesReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SalesReportResponse)
	err := c.cc.Invoke(ctx, Report_GetSalesReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) GetProductReport(ctx context.Context, in *GetProductReportRequest, opts ...grpc.CallOption) (*ProductReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductReportResponse)
	err := c.cc.Invoke(ctx, Report_GetProductReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) ExportOrderReport(ctx context.Context, in *ExportOrderReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportReportResponse)
	err := c.cc.Invoke(ctx, Report_ExportOrderReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) ExportUserReport(ctx context.Context, in *ExportUserReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportReportResponse)
	err := c.cc.Invoke(ctx, Report_ExportUserReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) ExportSalesReport(ctx context.Context, in *ExportSalesReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportReportResponse)
	err := c.cc.Invoke(ctx, Report_ExportSalesReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportClient) ExportProductReport(ctx context.Context, in *ExportProductReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportReportResponse)
	err := c.cc.Invoke(ctx, Report_ExportProductReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServer is the server API for Report service.
// All implementations must embed UnimplementedReportServer
// for forward compatibility.
type ReportServer interface {
	// 订单报表
	GetOrderReport(context.Context, *GetOrderReportRequest) (*OrderReportResponse, error)
	// 用户报表
	GetUserReport(context.Context, *GetUserReportRequest) (*UserReportResponse, error)
	// 销售报表
	GetSalesReport(context.Context, *GetSalesReportRequest) (*SalesReportResponse, error)
	// 商品报表
	GetProductReport(context.Context, *GetProductReportRequest) (*ProductReportResponse, error)
	// 导出订单报表到Excel
	ExportOrderReport(context.Context, *ExportOrderReportRequest) (*ExportReportResponse, error)
	// 导出用户报表到Excel
	ExportUserReport(context.Context, *ExportUserReportRequest) (*ExportReportResponse, error)
	// 导出销售报表到Excel
	ExportSalesReport(context.Context, *ExportSalesReportRequest) (*ExportReportResponse, error)
	// 导出商品报表到Excel
	ExportProductReport(context.Context, *ExportProductReportRequest) (*ExportReportResponse, error)
	mustEmbedUnimplementedReportServer()
}

// UnimplementedReportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportServer struct{}

func (UnimplementedReportServer) GetOrderReport(context.Context, *GetOrderReportRequest) (*OrderReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderReport not implemented")
}
func (UnimplementedReportServer) GetUserReport(context.Context, *GetUserReportRequest) (*UserReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserReport not implemented")
}
func (UnimplementedReportServer) GetSalesReport(context.Context, *GetSalesReportRequest) (*SalesReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSalesReport not implemented")
}
func (UnimplementedReportServer) GetProductReport(context.Context, *GetProductReportRequest) (*ProductReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductReport not implemented")
}
func (UnimplementedReportServer) ExportOrderReport(context.Context, *ExportOrderReportRequest) (*ExportReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportOrderReport not implemented")
}
func (UnimplementedReportServer) ExportUserReport(context.Context, *ExportUserReportRequest) (*ExportReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportUserReport not implemented")
}
func (UnimplementedReportServer) ExportSalesReport(context.Context, *ExportSalesReportRequest) (*ExportReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportSalesReport not implemented")
}
func (UnimplementedReportServer) ExportProductReport(context.Context, *ExportProductReportRequest) (*ExportReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportProductReport not implemented")
}
func (UnimplementedReportServer) mustEmbedUnimplementedReportServer() {}
func (UnimplementedReportServer) testEmbeddedByValue()                {}

// UnsafeReportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServer will
// result in compilation errors.
type UnsafeReportServer interface {
	mustEmbedUnimplementedReportServer()
}

func RegisterReportServer(s grpc.ServiceRegistrar, srv ReportServer) {
	// If the following call panics, it indicates UnimplementedReportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Report_ServiceDesc, srv)
}

func _Report_GetOrderReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).GetOrderReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_GetOrderReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).GetOrderReport(ctx, req.(*GetOrderReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_GetUserReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).GetUserReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_GetUserReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).GetUserReport(ctx, req.(*GetUserReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_GetSalesReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSalesReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).GetSalesReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_GetSalesReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).GetSalesReport(ctx, req.(*GetSalesReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_GetProductReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).GetProductReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_GetProductReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).GetProductReport(ctx, req.(*GetProductReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_ExportOrderReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportOrderReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).ExportOrderReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_ExportOrderReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).ExportOrderReport(ctx, req.(*ExportOrderReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_ExportUserReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportUserReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).ExportUserReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_ExportUserReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).ExportUserReport(ctx, req.(*ExportUserReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_ExportSalesReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSalesReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).ExportSalesReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_ExportSalesReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).ExportSalesReport(ctx, req.(*ExportSalesReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Report_ExportProductReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportProductReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).ExportProductReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Report_ExportProductReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).ExportProductReport(ctx, req.(*ExportProductReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Report_ServiceDesc is the grpc.ServiceDesc for Report service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Report_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "report.v1.Report",
	HandlerType: (*ReportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderReport",
			Handler:    _Report_GetOrderReport_Handler,
		},
		{
			MethodName: "GetUserReport",
			Handler:    _Report_GetUserReport_Handler,
		},
		{
			MethodName: "GetSalesReport",
			Handler:    _Report_GetSalesReport_Handler,
		},
		{
			MethodName: "GetProductReport",
			Handler:    _Report_GetProductReport_Handler,
		},
		{
			MethodName: "ExportOrderReport",
			Handler:    _Report_ExportOrderReport_Handler,
		},
		{
			MethodName: "ExportUserReport",
			Handler:    _Report_ExportUserReport_Handler,
		},
		{
			MethodName: "ExportSalesReport",
			Handler:    _Report_ExportSalesReport_Handler,
		},
		{
			MethodName: "ExportProductReport",
			Handler:    _Report_ExportProductReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report/v1/report.proto",
}
