// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"user/internal/biz"
	"user/internal/conf"
	"user/internal/data"
	"user/internal/server"
	"user/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.Jwt, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	configRepo := data.NewConfigRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, configRepo, logger)
	jwtManager := service.NewJWTManagerProvider(jwt)
	captchaManager := service.NewCaptchaManagerProvider()
	userService := service.NewUserService(userUsecase, jwtManager, captchaManager, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, jwtManager, logger)
	httpServer := server.NewHTTPServer(confServer, userService, jwtManager, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
