// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"sms/internal/biz"
	"sms/internal/conf"
	"sms/internal/data"
	"sms/internal/server"
	"sms/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, sms *conf.Sms, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	smsRepo := data.NewSmsRepo(dataData, logger)
	smsUsecase, err := biz.NewSmsUsecase(smsRepo, sms, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	smsService := service.NewSmsService(smsUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, smsService, logger)
	httpServer := server.NewHTTPServer(confServer, smsService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
