// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"finance/internal/biz"
	"finance/internal/conf"
	"finance/internal/data"
	"finance/internal/server"
	"finance/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	rechargeRepo := data.NewRechargeRepo(dataData, logger)
	withdrawalRepo := data.NewWithdrawalRepo(dataData, logger)
	incomeLogRepo := data.NewIncomeLogRepo(dataData, logger)
	balanceLogRepo := data.NewBalanceLogRepo(dataData, logger)
	checkInRepo := data.NewCheckInRepo(dataData, logger)
	financeUsecase := biz.NewFinanceUsecase(rechargeRepo, withdrawalRepo, incomeLogRepo, balanceLogRepo, checkInRepo, logger)
	financeService := service.NewFinanceService(financeUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, financeService, logger)
	httpServer := server.NewHTTPServer(confServer, financeService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
